; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27048.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG147594 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG147595 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG147596 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG147889 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG147890 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG147891 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG148184 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG148185 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG148186 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
?qt_meta_stringdata_EmotionWindow@@3Uqt_meta_stringdata_EmotionWindow_t@@B DD 0ffffffffH ; qt_meta_stringdata_EmotionWindow
	DD	0dH
	DD	00H
	ORG $+4
	DQ	0000000000000090H
	DD	0ffffffffH
	DD	017H
	DD	00H
	ORG $+4
	DQ	0000000000000086H
	DD	0ffffffffH
	DD	00H
	DD	00H
	ORG $+4
	DQ	0000000000000086H
	DD	0ffffffffH
	DD	018H
	DD	00H
	ORG $+4
	DQ	000000000000006fH
	DD	0ffffffffH
	DD	0aH
	DD	00H
	ORG $+4
	DQ	0000000000000070H
	DD	0ffffffffH
	DD	0aH
	DD	00H
	ORG $+4
	DQ	0000000000000063H
	DB	045H
	DB	06dH
	DB	06fH
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	057H
	DB	069H
	DB	06eH
	DB	064H
	DB	06fH
	DB	077H
	DB	00H
	DB	073H
	DB	069H
	DB	067H
	DB	06eH
	DB	061H
	DB	06cH
	DB	045H
	DB	06dH
	DB	06fH
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	057H
	DB	069H
	DB	06eH
	DB	064H
	DB	06fH
	DB	077H
	DB	048H
	DB	069H
	DB	064H
	DB	065H
	DB	00H
	DB	00H
	DB	073H
	DB	069H
	DB	067H
	DB	06eH
	DB	061H
	DB	06cH
	DB	045H
	DB	06dH
	DB	06fH
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	049H
	DB	074H
	DB	065H
	DB	06dH
	DB	043H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	00H
	DB	065H
	DB	06dH
	DB	06fH
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	04eH
	DB	075H
	DB	06dH
	DB	00H
	DB	061H
	DB	064H
	DB	064H
	DB	045H
	DB	06dH
	DB	06fH
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	00H
	ORG $+2
	ORG $+8
?qt_meta_data_EmotionWindow@@3QBIB DD 07H		; qt_meta_data_EmotionWindow
	DD	00H
	DD	00H
	DD	00H
	DD	03H
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	02H
	DD	01H
	DD	00H
	DD	01dH
	DD	02H
	DD	06H
	DD	03H
	DD	01H
	DD	01eH
	DD	02H
	DD	06H
	DD	05H
	DD	01H
	DD	021H
	DD	02H
	DD	08H
	DD	02bH
	DD	02bH
	DD	02H
	DD	04H
	DD	02bH
	DD	02H
	DD	04H
	DD	00H
	ORG $+4
$SG144297 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+5
$SG144298 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG144299 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG146227 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG146228 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG146229 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG146522 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG146523 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG146524 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG146817 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG146818 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG146819 DB	'qRegisterNormalizedMetaType', 00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@EmotionWindow@@UEBAPEBUQMetaObject@@XZ ; EmotionWindow::metaObject
PUBLIC	?qt_metacast@EmotionWindow@@UEAAPEAXPEBD@Z	; EmotionWindow::qt_metacast
PUBLIC	?qt_metacall@EmotionWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; EmotionWindow::qt_metacall
PUBLIC	?qt_static_metacall@EmotionWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; EmotionWindow::qt_static_metacall
PUBLIC	?signalEmotionWindowHide@EmotionWindow@@QEAAXXZ	; EmotionWindow::signalEmotionWindowHide
PUBLIC	?signalEmotionItemClicked@EmotionWindow@@QEAAXH@Z ; EmotionWindow::signalEmotionItemClicked
PUBLIC	?staticMetaObject@EmotionWindow@@2UQMetaObject@@B ; EmotionWindow::staticMetaObject
EXTRN	strcmp:PROC
EXTRN	__imp_?activate@QMetaObject@@SAXPEAVQObject@@PEBU1@HPEAPEAX@Z:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QWidget@@UEAAPEAXPEBD@Z:PROC
EXTRN	__imp_?qt_metacall@QWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC
EXTRN	?addEmotion@EmotionWindow@@AEAAXH@Z:PROC	; EmotionWindow::addEmotion
EXTRN	__imp_?staticMetaObject@QWidget@@2UQMetaObject@@B:BYTE
_BSS	SEGMENT
?staticMetaObject@EmotionWindow@@2UQMetaObject@@B DB 030H DUP (?) ; EmotionWindow::staticMetaObject
_BSS	ENDS
pdata	SEGMENT
$pdata$?metaObject@EmotionWindow@@UEBAPEBUQMetaObject@@XZ DD imagerel $LN5
	DD	imagerel $LN5+88
	DD	imagerel $unwind$?metaObject@EmotionWindow@@UEBAPEBUQMetaObject@@XZ
$pdata$?qt_metacast@EmotionWindow@@UEAAPEAXPEBD@Z DD imagerel $LN5
	DD	imagerel $LN5+75
	DD	imagerel $unwind$?qt_metacast@EmotionWindow@@UEAAPEAXPEBD@Z
$pdata$?qt_metacall@EmotionWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN9
	DD	imagerel $LN9+174
	DD	imagerel $unwind$?qt_metacall@EmotionWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?qt_static_metacall@EmotionWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN20
	DD	imagerel $LN20+498
	DD	imagerel $unwind$?qt_static_metacall@EmotionWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?signalEmotionWindowHide@EmotionWindow@@QEAAXXZ DD imagerel $LN3
	DD	imagerel $LN3+38
	DD	imagerel $unwind$?signalEmotionWindowHide@EmotionWindow@@QEAAXXZ
$pdata$?signalEmotionItemClicked@EmotionWindow@@QEAAXH@Z DD imagerel $LN3
	DD	imagerel $LN3+66
	DD	imagerel $unwind$?signalEmotionItemClicked@EmotionWindow@@QEAAXH@Z
pdata	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@EmotionWindow@@2P6AXXZEA@@3P6AXXZEA DQ FLAT:??__E?staticMetaObject@EmotionWindow@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@EmotionWindow@@2P6AXXZEA@@3P6AXXZEA
CRT$XCU	ENDS
xdata	SEGMENT
$unwind$?metaObject@EmotionWindow@@UEBAPEBUQMetaObject@@XZ DD 010901H
	DD	06209H
$unwind$?qt_metacast@EmotionWindow@@UEAAPEAXPEBD@Z DD 010e01H
	DD	0420eH
$unwind$?qt_metacall@EmotionWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	04217H
$unwind$?qt_static_metacall@EmotionWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	0c217H
$unwind$?signalEmotionWindowHide@EmotionWindow@@QEAAXXZ DD 010901H
	DD	04209H
$unwind$?signalEmotionItemClicked@EmotionWindow@@QEAAXH@Z DD 010d01H
	DD	0620dH
xdata	ENDS
; Function compile flags: /Odtp
;	COMDAT ??__E?staticMetaObject@EmotionWindow@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@EmotionWindow@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'EmotionWindow::staticMetaObject'', COMDAT
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_emotionwindow.cpp
; Line 109
	mov	rax, QWORD PTR __imp_?staticMetaObject@QWidget@@2UQMetaObject@@B
	mov	QWORD PTR ?staticMetaObject@EmotionWindow@@2UQMetaObject@@B, rax
	lea	rax, OFFSET FLAT:?qt_meta_stringdata_EmotionWindow@@3Uqt_meta_stringdata_EmotionWindow_t@@B
	mov	QWORD PTR ?staticMetaObject@EmotionWindow@@2UQMetaObject@@B+8, rax
; Line 110
	lea	rax, OFFSET FLAT:?qt_meta_data_EmotionWindow@@3QBIB
	mov	QWORD PTR ?staticMetaObject@EmotionWindow@@2UQMetaObject@@B+16, rax
	lea	rax, OFFSET FLAT:?qt_static_metacall@EmotionWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; EmotionWindow::qt_static_metacall
	mov	QWORD PTR ?staticMetaObject@EmotionWindow@@2UQMetaObject@@B+24, rax
	mov	QWORD PTR ?staticMetaObject@EmotionWindow@@2UQMetaObject@@B+32, 0
	mov	QWORD PTR ?staticMetaObject@EmotionWindow@@2UQMetaObject@@B+40, 0
	ret	0
??__E?staticMetaObject@EmotionWindow@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'EmotionWindow::staticMetaObject''
text$di	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_a$ = 32
this$ = 64
_t1$ = 72
?signalEmotionItemClicked@EmotionWindow@@QEAAXH@Z PROC	; EmotionWindow::signalEmotionItemClicked
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_emotionwindow.cpp
; Line 152
$LN3:
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 153
	mov	QWORD PTR _a$[rsp], 0
	lea	rax, QWORD PTR _t1$[rsp]
	mov	QWORD PTR _a$[rsp+8], rax
; Line 154
	lea	r9, QWORD PTR _a$[rsp]
	mov	r8d, 1
	lea	rdx, OFFSET FLAT:?staticMetaObject@EmotionWindow@@2UQMetaObject@@B ; EmotionWindow::staticMetaObject
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?activate@QMetaObject@@SAXPEAVQObject@@PEBU1@HPEAPEAX@Z
; Line 155
	add	rsp, 56					; 00000038H
	ret	0
?signalEmotionItemClicked@EmotionWindow@@QEAAXH@Z ENDP	; EmotionWindow::signalEmotionItemClicked
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
?signalEmotionWindowHide@EmotionWindow@@QEAAXXZ PROC	; EmotionWindow::signalEmotionWindowHide
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_emotionwindow.cpp
; Line 146
$LN3:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 147
	xor	r9d, r9d
	xor	r8d, r8d
	lea	rdx, OFFSET FLAT:?staticMetaObject@EmotionWindow@@2UQMetaObject@@B ; EmotionWindow::staticMetaObject
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?activate@QMetaObject@@SAXPEAVQObject@@PEBU1@HPEAPEAX@Z
; Line 148
	add	rsp, 40					; 00000028H
	ret	0
?signalEmotionWindowHide@EmotionWindow@@QEAAXXZ ENDP	; EmotionWindow::signalEmotionWindowHide
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv69 = 32
tv131 = 36
tv145 = 40
_t$1 = 48
result$2 = 56
$T3 = 64
$T4 = 80
_o$ = 112
_c$ = 120
_id$ = 128
_a$ = 136
?qt_static_metacall@EmotionWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; EmotionWindow::qt_static_metacall
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_emotionwindow.cpp
; Line 79
$LN20:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 104				; 00000068H
; Line 80
	cmp	DWORD PTR _c$[rsp], 0
	jne	$LN4@qt_static_
; Line 81
	mov	rax, QWORD PTR _o$[rsp]
	mov	QWORD PTR _t$1[rsp], rax
; Line 83
	mov	eax, DWORD PTR _id$[rsp]
	mov	DWORD PTR tv69[rsp], eax
	cmp	DWORD PTR tv69[rsp], 0
	je	SHORT $LN6@qt_static_
	cmp	DWORD PTR tv69[rsp], 1
	je	SHORT $LN7@qt_static_
	cmp	DWORD PTR tv69[rsp], 2
	je	SHORT $LN8@qt_static_
	jmp	SHORT $LN9@qt_static_
$LN6@qt_static_:
; Line 84
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?signalEmotionWindowHide@EmotionWindow@@QEAAXXZ ; EmotionWindow::signalEmotionWindowHide
	jmp	SHORT $LN2@qt_static_
$LN7@qt_static_:
; Line 85
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?signalEmotionItemClicked@EmotionWindow@@QEAAXH@Z ; EmotionWindow::signalEmotionItemClicked
	jmp	SHORT $LN2@qt_static_
$LN8@qt_static_:
; Line 86
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?addEmotion@EmotionWindow@@AEAAXH@Z	; EmotionWindow::addEmotion
$LN9@qt_static_:
$LN2@qt_static_:
; Line 89
	jmp	$LN5@qt_static_
$LN4@qt_static_:
	cmp	DWORD PTR _c$[rsp], 10
	jne	$LN10@qt_static_
; Line 90
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	QWORD PTR result$2[rsp], rax
; Line 93
	lea	rax, OFFSET FLAT:?signalEmotionWindowHide@EmotionWindow@@QEAAXXZ ; EmotionWindow::signalEmotionWindowHide
	mov	QWORD PTR $T3[rsp], rax
	mov	DWORD PTR $T3[rsp+8], 0
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	rcx, QWORD PTR $T3[rsp]
	cmp	QWORD PTR [rax], rcx
	jne	SHORT $LN15@qt_static_
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	cmp	QWORD PTR [rax], 0
	je	SHORT $LN14@qt_static_
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	ecx, DWORD PTR $T3[rsp+8]
	cmp	DWORD PTR [rax+8], ecx
	jne	SHORT $LN15@qt_static_
$LN14@qt_static_:
	mov	DWORD PTR tv131[rsp], 1
	jmp	SHORT $LN16@qt_static_
$LN15@qt_static_:
	mov	DWORD PTR tv131[rsp], 0
$LN16@qt_static_:
	cmp	DWORD PTR tv131[rsp], 0
	je	SHORT $LN11@qt_static_
; Line 94
	mov	rax, QWORD PTR result$2[rsp]
	mov	DWORD PTR [rax], 0
; Line 95
	jmp	$LN1@qt_static_
$LN11@qt_static_:
; Line 100
	lea	rax, OFFSET FLAT:?signalEmotionItemClicked@EmotionWindow@@QEAAXH@Z ; EmotionWindow::signalEmotionItemClicked
	mov	QWORD PTR $T4[rsp], rax
	mov	DWORD PTR $T4[rsp+8], 0
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	rcx, QWORD PTR $T4[rsp]
	cmp	QWORD PTR [rax], rcx
	jne	SHORT $LN18@qt_static_
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	cmp	QWORD PTR [rax], 0
	je	SHORT $LN17@qt_static_
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	ecx, DWORD PTR $T4[rsp+8]
	cmp	DWORD PTR [rax+8], ecx
	jne	SHORT $LN18@qt_static_
$LN17@qt_static_:
	mov	DWORD PTR tv145[rsp], 1
	jmp	SHORT $LN19@qt_static_
$LN18@qt_static_:
	mov	DWORD PTR tv145[rsp], 0
$LN19@qt_static_:
	cmp	DWORD PTR tv145[rsp], 0
	je	SHORT $LN12@qt_static_
; Line 101
	mov	rax, QWORD PTR result$2[rsp]
	mov	DWORD PTR [rax], 1
$LN12@qt_static_:
$LN10@qt_static_:
$LN5@qt_static_:
$LN1@qt_static_:
; Line 106
	add	rsp, 104				; 00000068H
	ret	0
?qt_static_metacall@EmotionWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; EmotionWindow::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@EmotionWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; EmotionWindow::qt_metacall
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_emotionwindow.cpp
; Line 128
$LN9:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 129
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacall@QWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
	mov	DWORD PTR _id$[rsp], eax
; Line 130
	cmp	DWORD PTR _id$[rsp], 0
	jge	SHORT $LN2@qt_metacal
; Line 131
	mov	eax, DWORD PTR _id$[rsp]
	jmp	SHORT $LN1@qt_metacal
$LN2@qt_metacal:
; Line 132
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN3@qt_metacal
; Line 133
	cmp	DWORD PTR _id$[rsp], 3
	jge	SHORT $LN5@qt_metacal
; Line 134
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_static_metacall@EmotionWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; EmotionWindow::qt_static_metacall
$LN5@qt_metacal:
; Line 135
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 3
	mov	DWORD PTR _id$[rsp], eax
	jmp	SHORT $LN4@qt_metacal
$LN3@qt_metacal:
; Line 136
	cmp	DWORD PTR _c$[rsp], 12
	jne	SHORT $LN6@qt_metacal
; Line 137
	cmp	DWORD PTR _id$[rsp], 3
	jge	SHORT $LN7@qt_metacal
; Line 138
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	DWORD PTR [rax], -1
$LN7@qt_metacal:
; Line 139
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 3
	mov	DWORD PTR _id$[rsp], eax
$LN6@qt_metacal:
$LN4@qt_metacal:
; Line 141
	mov	eax, DWORD PTR _id$[rsp]
$LN1@qt_metacal:
; Line 142
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacall@EmotionWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; EmotionWindow::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_clname$ = 56
?qt_metacast@EmotionWindow@@UEAAPEAXPEBD@Z PROC		; EmotionWindow::qt_metacast
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_emotionwindow.cpp
; Line 120
$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 121
	cmp	QWORD PTR _clname$[rsp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 122
	lea	rdx, OFFSET FLAT:?qt_meta_stringdata_EmotionWindow@@3Uqt_meta_stringdata_EmotionWindow_t@@B+144
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 123
	mov	rax, QWORD PTR this$[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 124
	mov	rdx, QWORD PTR _clname$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacast@QWidget@@UEAAPEAXPEBD@Z
$LN1@qt_metacas:
; Line 125
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacast@EmotionWindow@@UEAAPEAXPEBD@Z ENDP		; EmotionWindow::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = 32
this$ = 64
?metaObject@EmotionWindow@@UEBAPEBUQMetaObject@@XZ PROC	; EmotionWindow::metaObject
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_emotionwindow.cpp
; Line 115
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 116
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	QWORD PTR [rax+40], 0
	je	SHORT $LN3@metaObject
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	rcx, rax
	call	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
	mov	QWORD PTR tv82[rsp], rax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@EmotionWindow@@2UQMetaObject@@B ; EmotionWindow::staticMetaObject
	mov	QWORD PTR tv82[rsp], rax
$LN4@metaObject:
	mov	rax, QWORD PTR tv82[rsp]
; Line 117
	add	rsp, 56					; 00000038H
	ret	0
?metaObject@EmotionWindow@@UEBAPEBUQMetaObject@@XZ ENDP	; EmotionWindow::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File e:\qt\5.9.6\msvc2017_64\include\qtcore\qscopedpointer.h
; Line 117
	mov	QWORD PTR [rsp+8], rcx
; Line 118
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 8
__formal$ = 16
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_emotionwindow.cpp
; Line 158
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 8
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_emotionwindow.cpp
; Line 158
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
