; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27048.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	?staticMetaObject@CCMainWindow@@2UQMetaObject@@B ; CCMainWindow::staticMetaObject
PUBLIC	?qt_static_metacall@CCMainWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; CCMainWindow::qt_static_metacall
EXTRN	?staticMetaObject@BasicWindow@@2UQMetaObject@@B:BYTE ; BasicWindow::staticMetaObject
CONST	SEGMENT
$SG155976 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG155977 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG155978 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG156271 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG156272 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG156273 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG156566 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG156567 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG156568 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
?staticMetaObject@CCMainWindow@@2UQMetaObject@@B DQ FLAT:?staticMetaObject@BasicWindow@@2UQMetaObject@@B ; CCMainWindow::staticMetaObject
	DQ	FLAT:?qt_meta_stringdata_CCMainWindow@@3Uqt_meta_stringdata_CCMainWindow_t@@B
	DQ	FLAT:?qt_meta_data_CCMainWindow@@3QBIB
	DQ	FLAT:?qt_static_metacall@CCMainWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
	DQ	0000000000000000H
	DQ	0000000000000000H
$SG156910 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG156911 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG156912 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
?qt_meta_stringdata_CCMainWindow@@3Uqt_meta_stringdata_CCMainWindow_t@@B DD 0ffffffffH ; qt_meta_stringdata_CCMainWindow
	DD	0cH
	DD	00H
	ORG $+4
	DQ	0000000000000108H
	DD	0ffffffffH
	DD	0dH
	DD	00H
	ORG $+4
	DQ	00000000000000fdH
	DD	0ffffffffH
	DD	00H
	DD	00H
	ORG $+4
	DQ	00000000000000f3H
	DD	0ffffffffH
	DD	010H
	DD	00H
	ORG $+4
	DQ	00000000000000dcH
	DD	0ffffffffH
	DD	04H
	DD	00H
	ORG $+4
	DQ	00000000000000d5H
	DD	0ffffffffH
	DD	06H
	DD	00H
	ORG $+4
	DQ	00000000000000c2H
	DD	0ffffffffH
	DD	0eH
	DD	00H
	ORG $+4
	DQ	00000000000000b1H
	DD	0ffffffffH
	DD	0fH
	DD	00H
	ORG $+4
	DQ	00000000000000a8H
	DD	0ffffffffH
	DD	013H
	DD	00H
	ORG $+4
	DQ	00000000000000a0H
	DD	0ffffffffH
	DD	05H
	DD	00H
	ORG $+4
	DQ	000000000000009cH
	DD	0ffffffffH
	DD	010H
	DD	00H
	ORG $+4
	DQ	000000000000008aH
	DB	043H
	DB	043H
	DB	04dH
	DB	061H
	DB	069H
	DB	06eH
	DB	057H
	DB	069H
	DB	06eH
	DB	064H
	DB	06fH
	DB	077H
	DB	00H
	DB	06fH
	DB	06eH
	DB	049H
	DB	074H
	DB	065H
	DB	06dH
	DB	043H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	00H
	DB	00H
	DB	051H
	DB	054H
	DB	072H
	DB	065H
	DB	065H
	DB	057H
	DB	069H
	DB	064H
	DB	067H
	DB	065H
	DB	074H
	DB	049H
	DB	074H
	DB	065H
	DB	06dH
	DB	02aH
	DB	00H
	DB	069H
	DB	074H
	DB	065H
	DB	06dH
	DB	00H
	DB	063H
	DB	06fH
	DB	06cH
	DB	075H
	DB	06dH
	DB	06eH
	DB	00H
	DB	06fH
	DB	06eH
	DB	049H
	DB	074H
	DB	065H
	DB	06dH
	DB	045H
	DB	078H
	DB	070H
	DB	061H
	DB	06eH
	DB	064H
	DB	065H
	DB	064H
	DB	00H
	DB	06fH
	DB	06eH
	DB	049H
	DB	074H
	DB	065H
	DB	06dH
	DB	043H
	DB	06fH
	DB	06cH
	DB	06cH
	DB	061H
	DB	070H
	DB	073H
	DB	065H
	DB	064H
	DB	00H
	DB	06fH
	DB	06eH
	DB	049H
	DB	074H
	DB	065H
	DB	06dH
	DB	044H
	DB	06fH
	DB	075H
	DB	062H
	DB	06cH
	DB	065H
	DB	043H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	00H
	DB	063H
	DB	06fH
	DB	06cH
	DB	075H
	DB	06dH
	DB	00H
	DB	06fH
	DB	06eH
	DB	041H
	DB	070H
	DB	070H
	DB	049H
	DB	063H
	DB	06fH
	DB	06eH
	DB	043H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	00H
	ORG $+5
?qt_meta_data_CCMainWindow@@3QBIB DD 07H		; qt_meta_data_CCMainWindow
	DD	00H
	DD	00H
	DD	00H
	DD	05H
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	02H
	DD	027H
	DD	02H
	DD	08H
	DD	06H
	DD	01H
	DD	02cH
	DD	02H
	DD	08H
	DD	07H
	DD	01H
	DD	02fH
	DD	02H
	DD	08H
	DD	08H
	DD	02H
	DD	032H
	DD	02H
	DD	08H
	DD	0aH
	DD	00H
	DD	037H
	DD	02H
	DD	08H
	DD	02bH
	DD	080000003H
	DD	02H
	DD	04H
	DD	05H
	DD	02bH
	DD	080000003H
	DD	04H
	DD	02bH
	DD	080000003H
	DD	04H
	DD	02bH
	DD	080000003H
	DD	02H
	DD	04H
	DD	09H
	DD	02bH
	DD	00H
	ORG $+4
$SG152494 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+5
$SG152495 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG152496 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG154609 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG154610 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG154611 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG154904 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG154905 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG154906 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG155199 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG155200 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG155201 DB	'qRegisterNormalizedMetaType', 00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@CCMainWindow@@UEBAPEBUQMetaObject@@XZ ; CCMainWindow::metaObject
PUBLIC	?qt_metacast@CCMainWindow@@UEAAPEAXPEBD@Z	; CCMainWindow::qt_metacast
PUBLIC	?qt_metacall@CCMainWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; CCMainWindow::qt_metacall
EXTRN	strcmp:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	?qt_metacast@BasicWindow@@UEAAPEAXPEBD@Z:PROC	; BasicWindow::qt_metacast
EXTRN	?qt_metacall@BasicWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC ; BasicWindow::qt_metacall
EXTRN	?onItemClicked@CCMainWindow@@AEAAXPEAVQTreeWidgetItem@@H@Z:PROC ; CCMainWindow::onItemClicked
EXTRN	?onItemExpanded@CCMainWindow@@AEAAXPEAVQTreeWidgetItem@@@Z:PROC ; CCMainWindow::onItemExpanded
EXTRN	?onItemCollapsed@CCMainWindow@@AEAAXPEAVQTreeWidgetItem@@@Z:PROC ; CCMainWindow::onItemCollapsed
EXTRN	?onItemDoubleClicked@CCMainWindow@@AEAAXPEAVQTreeWidgetItem@@H@Z:PROC ; CCMainWindow::onItemDoubleClicked
EXTRN	?onAppIconClicked@CCMainWindow@@AEAAXXZ:PROC	; CCMainWindow::onAppIconClicked
pdata	SEGMENT
$pdata$?metaObject@CCMainWindow@@UEBAPEBUQMetaObject@@XZ DD imagerel $LN5
	DD	imagerel $LN5+88
	DD	imagerel $unwind$?metaObject@CCMainWindow@@UEBAPEBUQMetaObject@@XZ
$pdata$?qt_metacast@CCMainWindow@@UEAAPEAXPEBD@Z DD imagerel $LN5
	DD	imagerel $LN5+74
	DD	imagerel $unwind$?qt_metacast@CCMainWindow@@UEAAPEAXPEBD@Z
$pdata$?qt_metacall@CCMainWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN9
	DD	imagerel $LN9+173
	DD	imagerel $unwind$?qt_metacall@CCMainWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?qt_static_metacall@CCMainWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN12
	DD	imagerel $LN12+292
	DD	imagerel $unwind$?qt_static_metacall@CCMainWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
pdata	ENDS
xdata	SEGMENT
$unwind$?metaObject@CCMainWindow@@UEBAPEBUQMetaObject@@XZ DD 010901H
	DD	06209H
$unwind$?qt_metacast@CCMainWindow@@UEAAPEAXPEBD@Z DD 010e01H
	DD	0420eH
$unwind$?qt_metacall@CCMainWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	04217H
$unwind$?qt_static_metacall@CCMainWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	06217H
xdata	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv69 = 32
_t$1 = 40
_o$ = 64
_c$ = 72
_id$ = 80
_a$ = 88
?qt_static_metacall@CCMainWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; CCMainWindow::qt_static_metacall
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_ccmainwindow.cpp
; Line 85
$LN12:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 86
	cmp	DWORD PTR _c$[rsp], 0
	jne	$LN4@qt_static_
; Line 87
	mov	rax, QWORD PTR _o$[rsp]
	mov	QWORD PTR _t$1[rsp], rax
; Line 89
	mov	eax, DWORD PTR _id$[rsp]
	mov	DWORD PTR tv69[rsp], eax
	cmp	DWORD PTR tv69[rsp], 0
	je	SHORT $LN5@qt_static_
	cmp	DWORD PTR tv69[rsp], 1
	je	SHORT $LN6@qt_static_
	cmp	DWORD PTR tv69[rsp], 2
	je	SHORT $LN7@qt_static_
	cmp	DWORD PTR tv69[rsp], 3
	je	$LN8@qt_static_
	cmp	DWORD PTR tv69[rsp], 4
	je	$LN9@qt_static_
	jmp	$LN10@qt_static_
$LN5@qt_static_:
; Line 90
	mov	eax, 8
	imul	rax, rax, 2
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	ecx, 8
	imul	rcx, rcx, 1
	mov	rdx, QWORD PTR _a$[rsp]
	mov	rcx, QWORD PTR [rdx+rcx]
	mov	r8d, DWORD PTR [rax]
	mov	rdx, QWORD PTR [rcx]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?onItemClicked@CCMainWindow@@AEAAXPEAVQTreeWidgetItem@@H@Z ; CCMainWindow::onItemClicked
	jmp	$LN2@qt_static_
$LN6@qt_static_:
; Line 91
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	rdx, QWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?onItemExpanded@CCMainWindow@@AEAAXPEAVQTreeWidgetItem@@@Z ; CCMainWindow::onItemExpanded
	jmp	SHORT $LN2@qt_static_
$LN7@qt_static_:
; Line 92
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	rdx, QWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?onItemCollapsed@CCMainWindow@@AEAAXPEAVQTreeWidgetItem@@@Z ; CCMainWindow::onItemCollapsed
	jmp	SHORT $LN2@qt_static_
$LN8@qt_static_:
; Line 93
	mov	eax, 8
	imul	rax, rax, 2
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	ecx, 8
	imul	rcx, rcx, 1
	mov	rdx, QWORD PTR _a$[rsp]
	mov	rcx, QWORD PTR [rdx+rcx]
	mov	r8d, DWORD PTR [rax]
	mov	rdx, QWORD PTR [rcx]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?onItemDoubleClicked@CCMainWindow@@AEAAXPEAVQTreeWidgetItem@@H@Z ; CCMainWindow::onItemDoubleClicked
	jmp	SHORT $LN2@qt_static_
$LN9@qt_static_:
; Line 94
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?onAppIconClicked@CCMainWindow@@AEAAXXZ	; CCMainWindow::onAppIconClicked
$LN10@qt_static_:
$LN2@qt_static_:
$LN4@qt_static_:
; Line 98
	add	rsp, 56					; 00000038H
	ret	0
?qt_static_metacall@CCMainWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; CCMainWindow::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@CCMainWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; CCMainWindow::qt_metacall
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_ccmainwindow.cpp
; Line 120
$LN9:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 121
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_metacall@BasicWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; BasicWindow::qt_metacall
	mov	DWORD PTR _id$[rsp], eax
; Line 122
	cmp	DWORD PTR _id$[rsp], 0
	jge	SHORT $LN2@qt_metacal
; Line 123
	mov	eax, DWORD PTR _id$[rsp]
	jmp	SHORT $LN1@qt_metacal
$LN2@qt_metacal:
; Line 124
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN3@qt_metacal
; Line 125
	cmp	DWORD PTR _id$[rsp], 5
	jge	SHORT $LN5@qt_metacal
; Line 126
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_static_metacall@CCMainWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; CCMainWindow::qt_static_metacall
$LN5@qt_metacal:
; Line 127
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 5
	mov	DWORD PTR _id$[rsp], eax
	jmp	SHORT $LN4@qt_metacal
$LN3@qt_metacal:
; Line 128
	cmp	DWORD PTR _c$[rsp], 12
	jne	SHORT $LN6@qt_metacal
; Line 129
	cmp	DWORD PTR _id$[rsp], 5
	jge	SHORT $LN7@qt_metacal
; Line 130
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	DWORD PTR [rax], -1
$LN7@qt_metacal:
; Line 131
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 5
	mov	DWORD PTR _id$[rsp], eax
$LN6@qt_metacal:
$LN4@qt_metacal:
; Line 133
	mov	eax, DWORD PTR _id$[rsp]
$LN1@qt_metacal:
; Line 134
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacall@CCMainWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; CCMainWindow::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_clname$ = 56
?qt_metacast@CCMainWindow@@UEAAPEAXPEBD@Z PROC		; CCMainWindow::qt_metacast
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_ccmainwindow.cpp
; Line 112
$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 113
	cmp	QWORD PTR _clname$[rsp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 114
	lea	rdx, OFFSET FLAT:?qt_meta_stringdata_CCMainWindow@@3Uqt_meta_stringdata_CCMainWindow_t@@B+264
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 115
	mov	rax, QWORD PTR this$[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 116
	mov	rdx, QWORD PTR _clname$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_metacast@BasicWindow@@UEAAPEAXPEBD@Z ; BasicWindow::qt_metacast
$LN1@qt_metacas:
; Line 117
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacast@CCMainWindow@@UEAAPEAXPEBD@Z ENDP		; CCMainWindow::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = 32
this$ = 64
?metaObject@CCMainWindow@@UEBAPEBUQMetaObject@@XZ PROC	; CCMainWindow::metaObject
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_ccmainwindow.cpp
; Line 107
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 108
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	QWORD PTR [rax+40], 0
	je	SHORT $LN3@metaObject
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	rcx, rax
	call	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
	mov	QWORD PTR tv82[rsp], rax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@CCMainWindow@@2UQMetaObject@@B ; CCMainWindow::staticMetaObject
	mov	QWORD PTR tv82[rsp], rax
$LN4@metaObject:
	mov	rax, QWORD PTR tv82[rsp]
; Line 109
	add	rsp, 56					; 00000038H
	ret	0
?metaObject@CCMainWindow@@UEBAPEBUQMetaObject@@XZ ENDP	; CCMainWindow::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File e:\qt\5.9.6\msvc2017_64\include\qtcore\qscopedpointer.h
; Line 117
	mov	QWORD PTR [rsp+8], rcx
; Line 118
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 8
__formal$ = 16
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_ccmainwindow.cpp
; Line 137
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 8
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_ccmainwindow.cpp
; Line 137
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
