; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27048.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	?staticMetaObject@ReceiveFile@@2UQMetaObject@@B	; ReceiveFile::staticMetaObject
PUBLIC	?qt_static_metacall@ReceiveFile@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; ReceiveFile::qt_static_metacall
EXTRN	?staticMetaObject@BasicWindow@@2UQMetaObject@@B:BYTE ; BasicWindow::staticMetaObject
CONST	SEGMENT
?staticMetaObject@ReceiveFile@@2UQMetaObject@@B DQ FLAT:?staticMetaObject@BasicWindow@@2UQMetaObject@@B ; ReceiveFile::staticMetaObject
	DQ	FLAT:?qt_meta_stringdata_ReceiveFile@@3Uqt_meta_stringdata_ReceiveFile_t@@B
	DQ	FLAT:?qt_meta_data_ReceiveFile@@3QBIB
	DQ	FLAT:?qt_static_metacall@ReceiveFile@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
	DQ	0000000000000000H
	DQ	0000000000000000H
?qt_meta_stringdata_ReceiveFile@@3Uqt_meta_stringdata_ReceiveFile_t@@B DD 0ffffffffH ; qt_meta_stringdata_ReceiveFile
	DD	0bH
	DD	00H
	ORG $+4
	DQ	0000000000000078H
	DD	0ffffffffH
	DD	0aH
	DD	00H
	ORG $+4
	DQ	000000000000006cH
	DD	0ffffffffH
	DD	00H
	DD	00H
	ORG $+4
	DQ	000000000000005fH
	DD	0ffffffffH
	DD	014H
	DD	00H
	ORG $+4
	DQ	0000000000000048H
	DD	0ffffffffH
	DD	010H
	DD	00H
	ORG $+4
	DQ	0000000000000045H
	DB	052H
	DB	065H
	DB	063H
	DB	065H
	DB	069H
	DB	076H
	DB	065H
	DB	046H
	DB	069H
	DB	06cH
	DB	065H
	DB	00H
	DB	072H
	DB	065H
	DB	066H
	DB	075H
	DB	073H
	DB	065H
	DB	046H
	DB	069H
	DB	06cH
	DB	065H
	DB	00H
	DB	00H
	DB	06fH
	DB	06eH
	DB	05fH
	DB	063H
	DB	061H
	DB	06eH
	DB	063H
	DB	065H
	DB	06cH
	DB	042H
	DB	074H
	DB	06eH
	DB	05fH
	DB	063H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	00H
	DB	06fH
	DB	06eH
	DB	05fH
	DB	06fH
	DB	06bH
	DB	042H
	DB	074H
	DB	06eH
	DB	05fH
	DB	063H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	00H
	ORG $+2
$SG143457 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+5
?qt_meta_data_ReceiveFile@@3QBIB DD 07H			; qt_meta_data_ReceiveFile
	DD	00H
	DD	00H
	DD	00H
	DD	03H
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	01H
	DD	00H
	DD	01dH
	DD	02H
	DD	06H
	DD	03H
	DD	00H
	DD	01eH
	DD	02H
	DD	08H
	DD	04H
	DD	00H
	DD	01fH
	DD	02H
	DD	08H
	DD	02bH
	DD	02bH
	DD	02bH
	DD	00H
	ORG $+12
$SG143458 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG143459 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG145387 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG145388 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG145389 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG145682 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG145683 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG145684 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG145977 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG145978 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG145979 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG146754 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG146755 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG146756 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG147049 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG147050 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG147051 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG147344 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG147345 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG147346 DB	'qRegisterNormalizedMetaType', 00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@ReceiveFile@@UEBAPEBUQMetaObject@@XZ ; ReceiveFile::metaObject
PUBLIC	?qt_metacast@ReceiveFile@@UEAAPEAXPEBD@Z	; ReceiveFile::qt_metacast
PUBLIC	?qt_metacall@ReceiveFile@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; ReceiveFile::qt_metacall
PUBLIC	?refuseFile@ReceiveFile@@QEAAXXZ		; ReceiveFile::refuseFile
EXTRN	strcmp:PROC
EXTRN	__imp_?activate@QMetaObject@@SAXPEAVQObject@@PEBU1@HPEAPEAX@Z:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	?qt_metacast@BasicWindow@@UEAAPEAXPEBD@Z:PROC	; BasicWindow::qt_metacast
EXTRN	?qt_metacall@BasicWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC ; BasicWindow::qt_metacall
EXTRN	?on_cancelBtn_clicked@ReceiveFile@@AEAAXXZ:PROC	; ReceiveFile::on_cancelBtn_clicked
EXTRN	?on_okBtn_clicked@ReceiveFile@@AEAAXXZ:PROC	; ReceiveFile::on_okBtn_clicked
pdata	SEGMENT
$pdata$?metaObject@ReceiveFile@@UEBAPEBUQMetaObject@@XZ DD imagerel $LN5
	DD	imagerel $LN5+88
	DD	imagerel $unwind$?metaObject@ReceiveFile@@UEBAPEBUQMetaObject@@XZ
$pdata$?qt_metacast@ReceiveFile@@UEAAPEAXPEBD@Z DD imagerel $LN5
	DD	imagerel $LN5+74
	DD	imagerel $unwind$?qt_metacast@ReceiveFile@@UEAAPEAXPEBD@Z
$pdata$?qt_metacall@ReceiveFile@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN9
	DD	imagerel $LN9+173
	DD	imagerel $unwind$?qt_metacall@ReceiveFile@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?qt_static_metacall@ReceiveFile@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN16
	DD	imagerel $LN16+284
	DD	imagerel $unwind$?qt_static_metacall@ReceiveFile@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?refuseFile@ReceiveFile@@QEAAXXZ DD imagerel $LN3
	DD	imagerel $LN3+38
	DD	imagerel $unwind$?refuseFile@ReceiveFile@@QEAAXXZ
pdata	ENDS
xdata	SEGMENT
$unwind$?metaObject@ReceiveFile@@UEBAPEBUQMetaObject@@XZ DD 010901H
	DD	06209H
$unwind$?qt_metacast@ReceiveFile@@UEAAPEAXPEBD@Z DD 010e01H
	DD	0420eH
$unwind$?qt_metacall@ReceiveFile@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	04217H
$unwind$?qt_static_metacall@ReceiveFile@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	0a217H
$unwind$?refuseFile@ReceiveFile@@QEAAXXZ DD 010901H
	DD	04209H
xdata	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
?refuseFile@ReceiveFile@@QEAAXXZ PROC			; ReceiveFile::refuseFile
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_receivefile.cpp
; Line 138
$LN3:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 139
	xor	r9d, r9d
	xor	r8d, r8d
	lea	rdx, OFFSET FLAT:?staticMetaObject@ReceiveFile@@2UQMetaObject@@B ; ReceiveFile::staticMetaObject
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?activate@QMetaObject@@SAXPEAVQObject@@PEBU1@HPEAPEAX@Z
; Line 140
	add	rsp, 40					; 00000028H
	ret	0
?refuseFile@ReceiveFile@@QEAAXXZ ENDP			; ReceiveFile::refuseFile
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv69 = 32
tv91 = 36
_t$1 = 40
result$2 = 48
$T3 = 56
_o$ = 96
_c$ = 104
_id$ = 112
_a$ = 120
?qt_static_metacall@ReceiveFile@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; ReceiveFile::qt_static_metacall
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_receivefile.cpp
; Line 77
$LN16:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 88					; 00000058H
; Line 78
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN4@qt_static_
; Line 79
	mov	rax, QWORD PTR _o$[rsp]
	mov	QWORD PTR _t$1[rsp], rax
; Line 81
	mov	eax, DWORD PTR _id$[rsp]
	mov	DWORD PTR tv69[rsp], eax
	cmp	DWORD PTR tv69[rsp], 0
	je	SHORT $LN6@qt_static_
	cmp	DWORD PTR tv69[rsp], 1
	je	SHORT $LN7@qt_static_
	cmp	DWORD PTR tv69[rsp], 2
	je	SHORT $LN8@qt_static_
	jmp	SHORT $LN9@qt_static_
$LN6@qt_static_:
; Line 82
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?refuseFile@ReceiveFile@@QEAAXXZ	; ReceiveFile::refuseFile
	jmp	SHORT $LN2@qt_static_
$LN7@qt_static_:
; Line 83
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?on_cancelBtn_clicked@ReceiveFile@@AEAAXXZ ; ReceiveFile::on_cancelBtn_clicked
	jmp	SHORT $LN2@qt_static_
$LN8@qt_static_:
; Line 84
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?on_okBtn_clicked@ReceiveFile@@AEAAXXZ	; ReceiveFile::on_okBtn_clicked
$LN9@qt_static_:
$LN2@qt_static_:
; Line 87
	jmp	$LN5@qt_static_
$LN4@qt_static_:
	cmp	DWORD PTR _c$[rsp], 10
	jne	$LN10@qt_static_
; Line 88
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	QWORD PTR result$2[rsp], rax
; Line 91
	lea	rax, OFFSET FLAT:?refuseFile@ReceiveFile@@QEAAXXZ ; ReceiveFile::refuseFile
	mov	QWORD PTR $T3[rsp], rax
	mov	DWORD PTR $T3[rsp+8], 0
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	rcx, QWORD PTR $T3[rsp]
	cmp	QWORD PTR [rax], rcx
	jne	SHORT $LN14@qt_static_
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	cmp	QWORD PTR [rax], 0
	je	SHORT $LN13@qt_static_
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	ecx, DWORD PTR $T3[rsp+8]
	cmp	DWORD PTR [rax+8], ecx
	jne	SHORT $LN14@qt_static_
$LN13@qt_static_:
	mov	DWORD PTR tv91[rsp], 1
	jmp	SHORT $LN15@qt_static_
$LN14@qt_static_:
	mov	DWORD PTR tv91[rsp], 0
$LN15@qt_static_:
	cmp	DWORD PTR tv91[rsp], 0
	je	SHORT $LN11@qt_static_
; Line 92
	mov	rax, QWORD PTR result$2[rsp]
	mov	DWORD PTR [rax], 0
$LN11@qt_static_:
$LN10@qt_static_:
$LN5@qt_static_:
; Line 98
	add	rsp, 88					; 00000058H
	ret	0
?qt_static_metacall@ReceiveFile@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; ReceiveFile::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@ReceiveFile@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; ReceiveFile::qt_metacall
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_receivefile.cpp
; Line 120
$LN9:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 121
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_metacall@BasicWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; BasicWindow::qt_metacall
	mov	DWORD PTR _id$[rsp], eax
; Line 122
	cmp	DWORD PTR _id$[rsp], 0
	jge	SHORT $LN2@qt_metacal
; Line 123
	mov	eax, DWORD PTR _id$[rsp]
	jmp	SHORT $LN1@qt_metacal
$LN2@qt_metacal:
; Line 124
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN3@qt_metacal
; Line 125
	cmp	DWORD PTR _id$[rsp], 3
	jge	SHORT $LN5@qt_metacal
; Line 126
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_static_metacall@ReceiveFile@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; ReceiveFile::qt_static_metacall
$LN5@qt_metacal:
; Line 127
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 3
	mov	DWORD PTR _id$[rsp], eax
	jmp	SHORT $LN4@qt_metacal
$LN3@qt_metacal:
; Line 128
	cmp	DWORD PTR _c$[rsp], 12
	jne	SHORT $LN6@qt_metacal
; Line 129
	cmp	DWORD PTR _id$[rsp], 3
	jge	SHORT $LN7@qt_metacal
; Line 130
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	DWORD PTR [rax], -1
$LN7@qt_metacal:
; Line 131
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 3
	mov	DWORD PTR _id$[rsp], eax
$LN6@qt_metacal:
$LN4@qt_metacal:
; Line 133
	mov	eax, DWORD PTR _id$[rsp]
$LN1@qt_metacal:
; Line 134
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacall@ReceiveFile@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; ReceiveFile::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_clname$ = 56
?qt_metacast@ReceiveFile@@UEAAPEAXPEBD@Z PROC		; ReceiveFile::qt_metacast
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_receivefile.cpp
; Line 112
$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 113
	cmp	QWORD PTR _clname$[rsp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 114
	lea	rdx, OFFSET FLAT:?qt_meta_stringdata_ReceiveFile@@3Uqt_meta_stringdata_ReceiveFile_t@@B+120
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 115
	mov	rax, QWORD PTR this$[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 116
	mov	rdx, QWORD PTR _clname$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_metacast@BasicWindow@@UEAAPEAXPEBD@Z ; BasicWindow::qt_metacast
$LN1@qt_metacas:
; Line 117
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacast@ReceiveFile@@UEAAPEAXPEBD@Z ENDP		; ReceiveFile::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = 32
this$ = 64
?metaObject@ReceiveFile@@UEBAPEBUQMetaObject@@XZ PROC	; ReceiveFile::metaObject
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_receivefile.cpp
; Line 107
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 108
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	QWORD PTR [rax+40], 0
	je	SHORT $LN3@metaObject
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	rcx, rax
	call	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
	mov	QWORD PTR tv82[rsp], rax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@ReceiveFile@@2UQMetaObject@@B ; ReceiveFile::staticMetaObject
	mov	QWORD PTR tv82[rsp], rax
$LN4@metaObject:
	mov	rax, QWORD PTR tv82[rsp]
; Line 109
	add	rsp, 56					; 00000038H
	ret	0
?metaObject@ReceiveFile@@UEBAPEBUQMetaObject@@XZ ENDP	; ReceiveFile::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File e:\qt\5.9.6\msvc2017_64\include\qtcore\qscopedpointer.h
; Line 117
	mov	QWORD PTR [rsp+8], rcx
; Line 118
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 8
__formal$ = 16
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_receivefile.cpp
; Line 143
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 8
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_receivefile.cpp
; Line 143
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
