; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27048.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
?qt_meta_stringdata_QMsgTextEdit@@3Uqt_meta_stringdata_QMsgTextEdit_t@@B DD 0ffffffffH ; qt_meta_stringdata_QMsgTextEdit
	DD	0cH
	DD	00H
	ORG $+4
	DQ	0000000000000060H
	DD	0ffffffffH
	DD	019H
	DD	00H
	ORG $+4
	DQ	0000000000000055H
	DD	0ffffffffH
	DD	00H
	DD	00H
	ORG $+4
	DQ	0000000000000057H
	DD	0ffffffffH
	DD	05H
	DD	00H
	ORG $+4
	DQ	0000000000000040H
	DB	051H
	DB	04dH
	DB	073H
	DB	067H
	DB	054H
	DB	065H
	DB	078H
	DB	074H
	DB	045H
	DB	064H
	DB	069H
	DB	074H
	DB	00H
	DB	06fH
	DB	06eH
	DB	045H
	DB	06dH
	DB	06fH
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	049H
	DB	06dH
	DB	061H
	DB	067H
	DB	065H
	DB	046H
	DB	072H
	DB	061H
	DB	06dH
	DB	065H
	DB	043H
	DB	068H
	DB	061H
	DB	06eH
	DB	067H
	DB	065H
	DB	00H
	DB	00H
	DB	066H
	DB	072H
	DB	061H
	DB	06dH
	DB	065H
	DB	00H
	ORG $+2
?qt_meta_data_QMsgTextEdit@@3QBIB DD 07H		; qt_meta_data_QMsgTextEdit
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	01H
	DD	013H
	DD	02H
	DD	08H
	DD	02bH
	DD	02H
	DD	03H
	DD	00H
	ORG $+4
$SG134320 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG134321 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG134322 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG136276 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG136277 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG136278 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG136571 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG136572 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG136573 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG136866 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG136867 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG136868 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG137654 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG137655 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG137656 DB	'qRegisterNormalizedMetaType', 00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@QMsgTextEdit@@UEBAPEBUQMetaObject@@XZ ; QMsgTextEdit::metaObject
PUBLIC	?qt_metacast@QMsgTextEdit@@UEAAPEAXPEBD@Z	; QMsgTextEdit::qt_metacast
PUBLIC	?qt_metacall@QMsgTextEdit@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; QMsgTextEdit::qt_metacall
PUBLIC	?qt_static_metacall@QMsgTextEdit@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; QMsgTextEdit::qt_static_metacall
PUBLIC	?staticMetaObject@QMsgTextEdit@@2UQMetaObject@@B ; QMsgTextEdit::staticMetaObject
EXTRN	strcmp:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QTextEdit@@UEAAPEAXPEBD@Z:PROC
EXTRN	__imp_?qt_metacall@QTextEdit@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC
EXTRN	?onEmotionImageFrameChange@QMsgTextEdit@@AEAAXH@Z:PROC ; QMsgTextEdit::onEmotionImageFrameChange
EXTRN	__imp_?staticMetaObject@QTextEdit@@2UQMetaObject@@B:BYTE
_BSS	SEGMENT
?staticMetaObject@QMsgTextEdit@@2UQMetaObject@@B DB 030H DUP (?) ; QMsgTextEdit::staticMetaObject
_BSS	ENDS
pdata	SEGMENT
$pdata$?metaObject@QMsgTextEdit@@UEBAPEBUQMetaObject@@XZ DD imagerel $LN5
	DD	imagerel $LN5+88
	DD	imagerel $unwind$?metaObject@QMsgTextEdit@@UEBAPEBUQMetaObject@@XZ
$pdata$?qt_metacast@QMsgTextEdit@@UEAAPEAXPEBD@Z DD imagerel $LN5
	DD	imagerel $LN5+75
	DD	imagerel $unwind$?qt_metacast@QMsgTextEdit@@UEAAPEAXPEBD@Z
$pdata$?qt_metacall@QMsgTextEdit@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN9
	DD	imagerel $LN9+172
	DD	imagerel $unwind$?qt_metacall@QMsgTextEdit@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?qt_static_metacall@QMsgTextEdit@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN8
	DD	imagerel $LN8+92
	DD	imagerel $unwind$?qt_static_metacall@QMsgTextEdit@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
pdata	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@QMsgTextEdit@@2P6AXXZEA@@3P6AXXZEA DQ FLAT:??__E?staticMetaObject@QMsgTextEdit@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@QMsgTextEdit@@2P6AXXZEA@@3P6AXXZEA
CRT$XCU	ENDS
xdata	SEGMENT
$unwind$?metaObject@QMsgTextEdit@@UEBAPEBUQMetaObject@@XZ DD 010901H
	DD	06209H
$unwind$?qt_metacast@QMsgTextEdit@@UEAAPEAXPEBD@Z DD 010e01H
	DD	0420eH
$unwind$?qt_metacall@QMsgTextEdit@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	04217H
$unwind$?qt_static_metacall@QMsgTextEdit@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	06217H
xdata	ENDS
; Function compile flags: /Odtp
;	COMDAT ??__E?staticMetaObject@QMsgTextEdit@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@QMsgTextEdit@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'QMsgTextEdit::staticMetaObject'', COMDAT
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_qmsgtextedit.cpp
; Line 80
	mov	rax, QWORD PTR __imp_?staticMetaObject@QTextEdit@@2UQMetaObject@@B
	mov	QWORD PTR ?staticMetaObject@QMsgTextEdit@@2UQMetaObject@@B, rax
	lea	rax, OFFSET FLAT:?qt_meta_stringdata_QMsgTextEdit@@3Uqt_meta_stringdata_QMsgTextEdit_t@@B
	mov	QWORD PTR ?staticMetaObject@QMsgTextEdit@@2UQMetaObject@@B+8, rax
; Line 81
	lea	rax, OFFSET FLAT:?qt_meta_data_QMsgTextEdit@@3QBIB
	mov	QWORD PTR ?staticMetaObject@QMsgTextEdit@@2UQMetaObject@@B+16, rax
	lea	rax, OFFSET FLAT:?qt_static_metacall@QMsgTextEdit@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; QMsgTextEdit::qt_static_metacall
	mov	QWORD PTR ?staticMetaObject@QMsgTextEdit@@2UQMetaObject@@B+24, rax
	mov	QWORD PTR ?staticMetaObject@QMsgTextEdit@@2UQMetaObject@@B+32, 0
	mov	QWORD PTR ?staticMetaObject@QMsgTextEdit@@2UQMetaObject@@B+40, 0
	ret	0
??__E?staticMetaObject@QMsgTextEdit@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'QMsgTextEdit::staticMetaObject''
text$di	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv69 = 32
_t$1 = 40
_o$ = 64
_c$ = 72
_id$ = 80
_a$ = 88
?qt_static_metacall@QMsgTextEdit@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; QMsgTextEdit::qt_static_metacall
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_qmsgtextedit.cpp
; Line 68
$LN8:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 69
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN4@qt_static_
; Line 70
	mov	rax, QWORD PTR _o$[rsp]
	mov	QWORD PTR _t$1[rsp], rax
; Line 72
	mov	eax, DWORD PTR _id$[rsp]
	mov	DWORD PTR tv69[rsp], eax
	cmp	DWORD PTR tv69[rsp], 0
	je	SHORT $LN5@qt_static_
	jmp	SHORT $LN6@qt_static_
$LN5@qt_static_:
; Line 73
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?onEmotionImageFrameChange@QMsgTextEdit@@AEAAXH@Z ; QMsgTextEdit::onEmotionImageFrameChange
$LN6@qt_static_:
$LN4@qt_static_:
; Line 77
	add	rsp, 56					; 00000038H
	ret	0
?qt_static_metacall@QMsgTextEdit@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; QMsgTextEdit::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@QMsgTextEdit@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; QMsgTextEdit::qt_metacall
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_qmsgtextedit.cpp
; Line 99
$LN9:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 100
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacall@QTextEdit@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
	mov	DWORD PTR _id$[rsp], eax
; Line 101
	cmp	DWORD PTR _id$[rsp], 0
	jge	SHORT $LN2@qt_metacal
; Line 102
	mov	eax, DWORD PTR _id$[rsp]
	jmp	SHORT $LN1@qt_metacal
$LN2@qt_metacal:
; Line 103
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN3@qt_metacal
; Line 104
	cmp	DWORD PTR _id$[rsp], 1
	jge	SHORT $LN5@qt_metacal
; Line 105
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_static_metacall@QMsgTextEdit@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; QMsgTextEdit::qt_static_metacall
$LN5@qt_metacal:
; Line 106
	mov	eax, DWORD PTR _id$[rsp]
	dec	eax
	mov	DWORD PTR _id$[rsp], eax
	jmp	SHORT $LN4@qt_metacal
$LN3@qt_metacal:
; Line 107
	cmp	DWORD PTR _c$[rsp], 12
	jne	SHORT $LN6@qt_metacal
; Line 108
	cmp	DWORD PTR _id$[rsp], 1
	jge	SHORT $LN7@qt_metacal
; Line 109
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	DWORD PTR [rax], -1
$LN7@qt_metacal:
; Line 110
	mov	eax, DWORD PTR _id$[rsp]
	dec	eax
	mov	DWORD PTR _id$[rsp], eax
$LN6@qt_metacal:
$LN4@qt_metacal:
; Line 112
	mov	eax, DWORD PTR _id$[rsp]
$LN1@qt_metacal:
; Line 113
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacall@QMsgTextEdit@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; QMsgTextEdit::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_clname$ = 56
?qt_metacast@QMsgTextEdit@@UEAAPEAXPEBD@Z PROC		; QMsgTextEdit::qt_metacast
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_qmsgtextedit.cpp
; Line 91
$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 92
	cmp	QWORD PTR _clname$[rsp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 93
	lea	rdx, OFFSET FLAT:?qt_meta_stringdata_QMsgTextEdit@@3Uqt_meta_stringdata_QMsgTextEdit_t@@B+96
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 94
	mov	rax, QWORD PTR this$[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 95
	mov	rdx, QWORD PTR _clname$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacast@QTextEdit@@UEAAPEAXPEBD@Z
$LN1@qt_metacas:
; Line 96
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacast@QMsgTextEdit@@UEAAPEAXPEBD@Z ENDP		; QMsgTextEdit::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = 32
this$ = 64
?metaObject@QMsgTextEdit@@UEBAPEBUQMetaObject@@XZ PROC	; QMsgTextEdit::metaObject
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_qmsgtextedit.cpp
; Line 86
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 87
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	QWORD PTR [rax+40], 0
	je	SHORT $LN3@metaObject
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	rcx, rax
	call	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
	mov	QWORD PTR tv82[rsp], rax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@QMsgTextEdit@@2UQMetaObject@@B ; QMsgTextEdit::staticMetaObject
	mov	QWORD PTR tv82[rsp], rax
$LN4@metaObject:
	mov	rax, QWORD PTR tv82[rsp]
; Line 88
	add	rsp, 56					; 00000038H
	ret	0
?metaObject@QMsgTextEdit@@UEBAPEBUQMetaObject@@XZ ENDP	; QMsgTextEdit::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File e:\qt\5.9.6\msvc2017_64\include\qtcore\qscopedpointer.h
; Line 117
	mov	QWORD PTR [rsp+8], rcx
; Line 118
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 8
__formal$ = 16
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_qmsgtextedit.cpp
; Line 116
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 8
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_qmsgtextedit.cpp
; Line 116
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
