; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27048.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG172294 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG172295 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG172296 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG172589 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG172590 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG172591 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG172884 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG172885 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG172886 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG173661 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG173662 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG173663 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
?qt_meta_stringdata_TalkWindow@@3Uqt_meta_stringdata_TalkWindow_t@@B DD 0ffffffffH ; qt_meta_stringdata_TalkWindow
	DD	0aH
	DD	00H
	ORG $+4
	DQ	00000000000000c0H
	DD	0ffffffffH
	DD	014H
	DD	00H
	ORG $+4
	DQ	00000000000000b3H
	DD	0ffffffffH
	DD	00H
	DD	00H
	ORG $+4
	DQ	00000000000000b0H
	DD	0ffffffffH
	DD	010H
	DD	00H
	ORG $+4
	DQ	0000000000000099H
	DD	0ffffffffH
	DD	013H
	DD	00H
	ORG $+4
	DQ	0000000000000092H
	DD	0ffffffffH
	DD	010H
	DD	00H
	ORG $+4
	DQ	000000000000008eH
	DD	0ffffffffH
	DD	04H
	DD	00H
	ORG $+4
	DQ	0000000000000087H
	DD	0ffffffffH
	DD	06H
	DD	00H
	ORG $+4
	DQ	0000000000000074H
	DB	054H
	DB	061H
	DB	06cH
	DB	06bH
	DB	057H
	DB	069H
	DB	06eH
	DB	064H
	DB	06fH
	DB	077H
	DB	00H
	DB	06fH
	DB	06eH
	DB	046H
	DB	069H
	DB	06cH
	DB	065H
	DB	04fH
	DB	070H
	DB	065H
	DB	06eH
	DB	042H
	DB	074H
	DB	06eH
	DB	043H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	00H
	DB	00H
	DB	06fH
	DB	06eH
	DB	053H
	DB	065H
	DB	06eH
	DB	064H
	DB	042H
	DB	074H
	DB	06eH
	DB	043H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	00H
	DB	06fH
	DB	06eH
	DB	049H
	DB	074H
	DB	065H
	DB	06dH
	DB	044H
	DB	06fH
	DB	075H
	DB	062H
	DB	06cH
	DB	065H
	DB	043H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	00H
	DB	051H
	DB	054H
	DB	072H
	DB	065H
	DB	065H
	DB	057H
	DB	069H
	DB	064H
	DB	067H
	DB	065H
	DB	074H
	DB	049H
	DB	074H
	DB	065H
	DB	06dH
	DB	02aH
	DB	00H
	DB	069H
	DB	074H
	DB	065H
	DB	06dH
	DB	00H
	DB	063H
	DB	06fH
	DB	06cH
	DB	075H
	DB	06dH
	DB	06eH
	DB	00H
	ORG $+5
	ORG $+8
?qt_meta_data_TalkWindow@@3QBIB DD 07H			; qt_meta_data_TalkWindow
	DD	00H
	DD	00H
	DD	00H
	DD	03H
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	01H
	DD	01dH
	DD	02H
	DD	08H
	DD	03H
	DD	01H
	DD	020H
	DD	02H
	DD	08H
	DD	04H
	DD	02H
	DD	023H
	DD	02H
	DD	08H
	DD	02bH
	DD	01H
	DD	02H
	DD	02bH
	DD	01H
	DD	02H
	DD	02bH
	DD	080000005H
	DD	02H
	DD	06H
	DD	07H
	DD	00H
	ORG $+4
$SG173956 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+5
$SG173957 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG173958 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG174251 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG174252 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG174253 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG174594 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG174595 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG174596 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG174937 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG174938 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG174939 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG175281 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG175282 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG175283 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG175576 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG175577 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG175578 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG175920 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG175921 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG175922 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG176215 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG176216 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG176217 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG176640 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG176641 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG176642 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG176935 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG176936 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG176937 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG177230 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG177231 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG177232 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG177556 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG177557 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG177558 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG177851 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG177852 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG177853 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG169886 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG169887 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG169888 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG178195 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG178196 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG178197 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG178539 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG178540 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG178541 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG178834 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG178835 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG178836 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG179178 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG179179 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG179180 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG179522 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG179523 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG179524 DB	'qRegisterNormalizedMetaType', 00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@TalkWindow@@UEBAPEBUQMetaObject@@XZ	; TalkWindow::metaObject
PUBLIC	?qt_metacast@TalkWindow@@UEAAPEAXPEBD@Z		; TalkWindow::qt_metacast
PUBLIC	?qt_metacall@TalkWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; TalkWindow::qt_metacall
PUBLIC	?qt_static_metacall@TalkWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; TalkWindow::qt_static_metacall
PUBLIC	?staticMetaObject@TalkWindow@@2UQMetaObject@@B	; TalkWindow::staticMetaObject
EXTRN	strcmp:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QWidget@@UEAAPEAXPEBD@Z:PROC
EXTRN	__imp_?qt_metacall@QWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC
EXTRN	?onFileOpenBtnClicked@TalkWindow@@AEAAX_N@Z:PROC ; TalkWindow::onFileOpenBtnClicked
EXTRN	?onSendBtnClicked@TalkWindow@@AEAAX_N@Z:PROC	; TalkWindow::onSendBtnClicked
EXTRN	?onItemDoubleClicked@TalkWindow@@AEAAXPEAVQTreeWidgetItem@@H@Z:PROC ; TalkWindow::onItemDoubleClicked
EXTRN	__imp_?staticMetaObject@QWidget@@2UQMetaObject@@B:BYTE
_BSS	SEGMENT
?staticMetaObject@TalkWindow@@2UQMetaObject@@B DB 030H DUP (?) ; TalkWindow::staticMetaObject
_BSS	ENDS
pdata	SEGMENT
$pdata$?metaObject@TalkWindow@@UEBAPEBUQMetaObject@@XZ DD imagerel $LN5
	DD	imagerel $LN5+88
	DD	imagerel $unwind$?metaObject@TalkWindow@@UEBAPEBUQMetaObject@@XZ
$pdata$?qt_metacast@TalkWindow@@UEAAPEAXPEBD@Z DD imagerel $LN5
	DD	imagerel $LN5+75
	DD	imagerel $unwind$?qt_metacast@TalkWindow@@UEAAPEAXPEBD@Z
$pdata$?qt_metacall@TalkWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN9
	DD	imagerel $LN9+174
	DD	imagerel $unwind$?qt_metacall@TalkWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?qt_static_metacall@TalkWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN10
	DD	imagerel $LN10+198
	DD	imagerel $unwind$?qt_static_metacall@TalkWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
pdata	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@TalkWindow@@2P6AXXZEA@@3P6AXXZEA DQ FLAT:??__E?staticMetaObject@TalkWindow@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@TalkWindow@@2P6AXXZEA@@3P6AXXZEA
CRT$XCU	ENDS
xdata	SEGMENT
$unwind$?metaObject@TalkWindow@@UEBAPEBUQMetaObject@@XZ DD 010901H
	DD	06209H
$unwind$?qt_metacast@TalkWindow@@UEAAPEAXPEBD@Z DD 010e01H
	DD	0420eH
$unwind$?qt_metacall@TalkWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	04217H
$unwind$?qt_static_metacall@TalkWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	06217H
xdata	ENDS
; Function compile flags: /Odtp
;	COMDAT ??__E?staticMetaObject@TalkWindow@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@TalkWindow@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'TalkWindow::staticMetaObject'', COMDAT
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_talkwindow.cpp
; Line 91
	mov	rax, QWORD PTR __imp_?staticMetaObject@QWidget@@2UQMetaObject@@B
	mov	QWORD PTR ?staticMetaObject@TalkWindow@@2UQMetaObject@@B, rax
	lea	rax, OFFSET FLAT:?qt_meta_stringdata_TalkWindow@@3Uqt_meta_stringdata_TalkWindow_t@@B
	mov	QWORD PTR ?staticMetaObject@TalkWindow@@2UQMetaObject@@B+8, rax
; Line 92
	lea	rax, OFFSET FLAT:?qt_meta_data_TalkWindow@@3QBIB
	mov	QWORD PTR ?staticMetaObject@TalkWindow@@2UQMetaObject@@B+16, rax
	lea	rax, OFFSET FLAT:?qt_static_metacall@TalkWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; TalkWindow::qt_static_metacall
	mov	QWORD PTR ?staticMetaObject@TalkWindow@@2UQMetaObject@@B+24, rax
	mov	QWORD PTR ?staticMetaObject@TalkWindow@@2UQMetaObject@@B+32, 0
	mov	QWORD PTR ?staticMetaObject@TalkWindow@@2UQMetaObject@@B+40, 0
	ret	0
??__E?staticMetaObject@TalkWindow@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'TalkWindow::staticMetaObject''
text$di	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv69 = 32
_t$1 = 40
_o$ = 64
_c$ = 72
_id$ = 80
_a$ = 88
?qt_static_metacall@TalkWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; TalkWindow::qt_static_metacall
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_talkwindow.cpp
; Line 77
$LN10:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 78
	cmp	DWORD PTR _c$[rsp], 0
	jne	$LN4@qt_static_
; Line 79
	mov	rax, QWORD PTR _o$[rsp]
	mov	QWORD PTR _t$1[rsp], rax
; Line 81
	mov	eax, DWORD PTR _id$[rsp]
	mov	DWORD PTR tv69[rsp], eax
	cmp	DWORD PTR tv69[rsp], 0
	je	SHORT $LN5@qt_static_
	cmp	DWORD PTR tv69[rsp], 1
	je	SHORT $LN6@qt_static_
	cmp	DWORD PTR tv69[rsp], 2
	je	SHORT $LN7@qt_static_
	jmp	SHORT $LN8@qt_static_
$LN5@qt_static_:
; Line 82
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	movzx	edx, BYTE PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?onFileOpenBtnClicked@TalkWindow@@AEAAX_N@Z ; TalkWindow::onFileOpenBtnClicked
	jmp	SHORT $LN2@qt_static_
$LN6@qt_static_:
; Line 83
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	movzx	edx, BYTE PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?onSendBtnClicked@TalkWindow@@AEAAX_N@Z	; TalkWindow::onSendBtnClicked
	jmp	SHORT $LN2@qt_static_
$LN7@qt_static_:
; Line 84
	mov	eax, 8
	imul	rax, rax, 2
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	ecx, 8
	imul	rcx, rcx, 1
	mov	rdx, QWORD PTR _a$[rsp]
	mov	rcx, QWORD PTR [rdx+rcx]
	mov	r8d, DWORD PTR [rax]
	mov	rdx, QWORD PTR [rcx]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?onItemDoubleClicked@TalkWindow@@AEAAXPEAVQTreeWidgetItem@@H@Z ; TalkWindow::onItemDoubleClicked
$LN8@qt_static_:
$LN2@qt_static_:
$LN4@qt_static_:
; Line 88
	add	rsp, 56					; 00000038H
	ret	0
?qt_static_metacall@TalkWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; TalkWindow::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@TalkWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; TalkWindow::qt_metacall
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_talkwindow.cpp
; Line 110
$LN9:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 111
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacall@QWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
	mov	DWORD PTR _id$[rsp], eax
; Line 112
	cmp	DWORD PTR _id$[rsp], 0
	jge	SHORT $LN2@qt_metacal
; Line 113
	mov	eax, DWORD PTR _id$[rsp]
	jmp	SHORT $LN1@qt_metacal
$LN2@qt_metacal:
; Line 114
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN3@qt_metacal
; Line 115
	cmp	DWORD PTR _id$[rsp], 3
	jge	SHORT $LN5@qt_metacal
; Line 116
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_static_metacall@TalkWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; TalkWindow::qt_static_metacall
$LN5@qt_metacal:
; Line 117
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 3
	mov	DWORD PTR _id$[rsp], eax
	jmp	SHORT $LN4@qt_metacal
$LN3@qt_metacal:
; Line 118
	cmp	DWORD PTR _c$[rsp], 12
	jne	SHORT $LN6@qt_metacal
; Line 119
	cmp	DWORD PTR _id$[rsp], 3
	jge	SHORT $LN7@qt_metacal
; Line 120
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	DWORD PTR [rax], -1
$LN7@qt_metacal:
; Line 121
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 3
	mov	DWORD PTR _id$[rsp], eax
$LN6@qt_metacal:
$LN4@qt_metacal:
; Line 123
	mov	eax, DWORD PTR _id$[rsp]
$LN1@qt_metacal:
; Line 124
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacall@TalkWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; TalkWindow::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_clname$ = 56
?qt_metacast@TalkWindow@@UEAAPEAXPEBD@Z PROC		; TalkWindow::qt_metacast
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_talkwindow.cpp
; Line 102
$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 103
	cmp	QWORD PTR _clname$[rsp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 104
	lea	rdx, OFFSET FLAT:?qt_meta_stringdata_TalkWindow@@3Uqt_meta_stringdata_TalkWindow_t@@B+192
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 105
	mov	rax, QWORD PTR this$[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 106
	mov	rdx, QWORD PTR _clname$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacast@QWidget@@UEAAPEAXPEBD@Z
$LN1@qt_metacas:
; Line 107
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacast@TalkWindow@@UEAAPEAXPEBD@Z ENDP		; TalkWindow::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = 32
this$ = 64
?metaObject@TalkWindow@@UEBAPEBUQMetaObject@@XZ PROC	; TalkWindow::metaObject
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_talkwindow.cpp
; Line 97
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 98
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	QWORD PTR [rax+40], 0
	je	SHORT $LN3@metaObject
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	rcx, rax
	call	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
	mov	QWORD PTR tv82[rsp], rax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@TalkWindow@@2UQMetaObject@@B ; TalkWindow::staticMetaObject
	mov	QWORD PTR tv82[rsp], rax
$LN4@metaObject:
	mov	rax, QWORD PTR tv82[rsp]
; Line 99
	add	rsp, 56					; 00000038H
	ret	0
?metaObject@TalkWindow@@UEBAPEBUQMetaObject@@XZ ENDP	; TalkWindow::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File e:\qt\5.9.6\msvc2017_64\include\qtcore\qscopedpointer.h
; Line 117
	mov	QWORD PTR [rsp+8], rcx
; Line 118
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 8
__formal$ = 16
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_talkwindow.cpp
; Line 127
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 8
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_talkwindow.cpp
; Line 127
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
