; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27048.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	?staticMetaObject@SendFile@@2UQMetaObject@@B	; SendFile::staticMetaObject
PUBLIC	?qt_static_metacall@SendFile@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; SendFile::qt_static_metacall
EXTRN	?staticMetaObject@BasicWindow@@2UQMetaObject@@B:BYTE ; BasicWindow::staticMetaObject
CONST	SEGMENT
$SG148836 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG148837 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG148838 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG149131 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG149132 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG149133 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG149426 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG149427 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG149428 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG150203 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG150204 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG150205 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG150498 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG150499 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG150500 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG150793 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG150794 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG150795 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG151137 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG151138 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG151139 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
?staticMetaObject@SendFile@@2UQMetaObject@@B DQ FLAT:?staticMetaObject@BasicWindow@@2UQMetaObject@@B ; SendFile::staticMetaObject
	DQ	FLAT:?qt_meta_stringdata_SendFile@@3Uqt_meta_stringdata_SendFile_t@@B
	DQ	FLAT:?qt_meta_data_SendFile@@3QBIB
	DQ	FLAT:?qt_static_metacall@SendFile@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
	DQ	0000000000000000H
	DQ	0000000000000000H
?qt_meta_stringdata_SendFile@@3Uqt_meta_stringdata_SendFile_t@@B DD 0ffffffffH ; qt_meta_stringdata_SendFile
	DD	08H
	DD	00H
	ORG $+4
	DQ	00000000000000f0H
	DD	0ffffffffH
	DD	0fH
	DD	00H
	ORG $+4
	DQ	00000000000000e1H
	DD	0ffffffffH
	DD	00H
	DD	00H
	ORG $+4
	DQ	00000000000000d9H
	DD	0ffffffffH
	DD	08H
	DD	00H
	ORG $+4
	DQ	00000000000000c2H
	DD	0ffffffffH
	DD	07H
	DD	00H
	ORG $+4
	DQ	00000000000000b3H
	DD	0ffffffffH
	DD	04H
	DD	00H
	ORG $+4
	DQ	00000000000000a3H
	DD	0ffffffffH
	DD	07H
	DD	00H
	ORG $+4
	DQ	0000000000000090H
	DD	0ffffffffH
	DD	08H
	DD	00H
	ORG $+4
	DQ	0000000000000080H
	DD	0ffffffffH
	DD	012H
	DD	00H
	ORG $+4
	DQ	0000000000000071H
	DD	0ffffffffH
	DD	012H
	DD	00H
	ORG $+4
	DQ	000000000000006cH
	DB	053H
	DB	065H
	DB	06eH
	DB	064H
	DB	046H
	DB	069H
	DB	06cH
	DB	065H
	DB	00H
	DB	073H
	DB	065H
	DB	06eH
	DB	064H
	DB	046H
	DB	069H
	DB	06cH
	DB	065H
	DB	043H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	00H
	DB	00H
	DB	051H
	DB	053H
	DB	074H
	DB	072H
	DB	069H
	DB	06eH
	DB	067H
	DB	026H
	DB	00H
	DB	073H
	DB	074H
	DB	072H
	DB	044H
	DB	061H
	DB	074H
	DB	061H
	DB	00H
	DB	069H
	DB	06eH
	DB	074H
	DB	026H
	DB	00H
	DB	06dH
	DB	073H
	DB	067H
	DB	054H
	DB	074H
	DB	070H
	DB	065H
	DB	00H
	DB	066H
	DB	069H
	DB	06cH
	DB	065H
	DB	04eH
	DB	061H
	DB	06dH
	DB	065H
	DB	00H
	DB	06fH
	DB	06eH
	DB	05fH
	DB	06fH
	DB	070H
	DB	065H
	DB	06eH
	DB	042H
	DB	074H
	DB	06eH
	DB	05fH
	DB	063H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	00H
	DB	06fH
	DB	06eH
	DB	05fH
	DB	073H
	DB	065H
	DB	06eH
	DB	064H
	DB	042H
	DB	074H
	DB	06eH
	DB	05fH
	DB	063H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	00H
	ORG $+1
	ORG $+8
?qt_meta_data_SendFile@@3QBIB DD 07H			; qt_meta_data_SendFile
	DD	00H
	DD	00H
	DD	00H
	DD	03H
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	01H
	DD	03H
	DD	01dH
	DD	02H
	DD	06H
	DD	08H
	DD	00H
	DD	024H
	DD	02H
	DD	08H
	DD	09H
	DD	00H
	DD	025H
	DD	02H
	DD	08H
	DD	02bH
	DD	080000003H
	DD	080000005H
	DD	0aH
	DD	04H
	DD	06H
	DD	07H
	DD	02bH
	DD	02bH
	DD	00H
	ORG $+4
$SG146824 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG146825 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG146826 DB	'qRegisterNormalizedMetaType', 00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@SendFile@@UEBAPEBUQMetaObject@@XZ	; SendFile::metaObject
PUBLIC	?qt_metacast@SendFile@@UEAAPEAXPEBD@Z		; SendFile::qt_metacast
PUBLIC	?qt_metacall@SendFile@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; SendFile::qt_metacall
PUBLIC	?sendFileClicked@SendFile@@QEAAXAEAVQString@@AEAHV2@@Z ; SendFile::sendFileClicked
EXTRN	strcmp:PROC
EXTRN	__imp_?activate@QMetaObject@@SAXPEAVQObject@@PEBU1@HPEAPEAX@Z:PROC
EXTRN	__imp_??0QString@@QEAA@AEBV0@@Z:PROC
EXTRN	__imp_??1QString@@QEAA@XZ:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	?qt_metacast@BasicWindow@@UEAAPEAXPEBD@Z:PROC	; BasicWindow::qt_metacast
EXTRN	?qt_metacall@BasicWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC ; BasicWindow::qt_metacall
EXTRN	?on_openBtn_clicked@SendFile@@AEAAXXZ:PROC	; SendFile::on_openBtn_clicked
EXTRN	?on_sendBtn_clicked@SendFile@@AEAAXXZ:PROC	; SendFile::on_sendBtn_clicked
EXTRN	__GSHandlerCheck_EH:PROC
EXTRN	__security_check_cookie:PROC
EXTRN	__security_cookie:QWORD
pdata	SEGMENT
$pdata$?metaObject@SendFile@@UEBAPEBUQMetaObject@@XZ DD imagerel $LN5
	DD	imagerel $LN5+88
	DD	imagerel $unwind$?metaObject@SendFile@@UEBAPEBUQMetaObject@@XZ
$pdata$?qt_metacast@SendFile@@UEAAPEAXPEBD@Z DD imagerel $LN5
	DD	imagerel $LN5+74
	DD	imagerel $unwind$?qt_metacast@SendFile@@UEAAPEAXPEBD@Z
$pdata$?qt_metacall@SendFile@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN9
	DD	imagerel $LN9+173
	DD	imagerel $unwind$?qt_metacall@SendFile@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?qt_static_metacall@SendFile@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN17
	DD	imagerel $LN17+400
	DD	imagerel $unwind$?qt_static_metacall@SendFile@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?sendFileClicked@SendFile@@QEAAXAEAVQString@@AEAHV2@@Z DD imagerel $LN4
	DD	imagerel $LN4+143
	DD	imagerel $unwind$?sendFileClicked@SendFile@@QEAAXAEAVQString@@AEAHV2@@Z
pdata	ENDS
pdata	SEGMENT
$pdata$?dtor$0@?0??sendFileClicked@SendFile@@QEAAXAEAVQString@@AEAHV2@@Z@4HA DD imagerel ?dtor$0@?0??sendFileClicked@SendFile@@QEAAXAEAVQString@@AEAHV2@@Z@4HA
	DD	imagerel ?dtor$0@?0??sendFileClicked@SendFile@@QEAAXAEAVQString@@AEAHV2@@Z@4HA+25
	DD	imagerel $unwind$?dtor$0@?0??sendFileClicked@SendFile@@QEAAXAEAVQString@@AEAHV2@@Z@4HA
pdata	ENDS
CONST	SEGMENT
	ORG $+4
$cppxdata$?sendFileClicked@SendFile@@QEAAXAEAVQString@@AEAHV2@@Z DD 019930522H
	DD	01H
	DD	imagerel $stateUnwindMap$?sendFileClicked@SendFile@@QEAAXAEAVQString@@AEAHV2@@Z
	DD	00H
	DD	00H
	DD	03H
	DD	imagerel $ip2state$?sendFileClicked@SendFile@@QEAAXAEAVQString@@AEAHV2@@Z
	DD	020H
	DD	00H
	DD	01H
CONST	ENDS
xdata	SEGMENT
$unwind$?metaObject@SendFile@@UEBAPEBUQMetaObject@@XZ DD 010901H
	DD	06209H
$unwind$?qt_metacast@SendFile@@UEAAPEAXPEBD@Z DD 010e01H
	DD	0420eH
$unwind$?qt_metacall@SendFile@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	04217H
$unwind$?qt_static_metacall@SendFile@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	0c217H
$unwind$?sendFileClicked@SendFile@@QEAAXAEAVQString@@AEAHV2@@Z DD 013019H
	DD	0a218H
	DD	imagerel __GSHandlerCheck_EH
	DD	imagerel $cppxdata$?sendFileClicked@SendFile@@QEAAXAEAVQString@@AEAHV2@@Z
	DD	04aH
$stateUnwindMap$?sendFileClicked@SendFile@@QEAAXAEAVQString@@AEAHV2@@Z DD 0ffffffffH
	DD	imagerel ?dtor$0@?0??sendFileClicked@SendFile@@QEAAXAEAVQString@@AEAHV2@@Z@4HA
$ip2state$?sendFileClicked@SendFile@@QEAAXAEAVQString@@AEAHV2@@Z DD imagerel ?sendFileClicked@SendFile@@QEAAXAEAVQString@@AEAHV2@@Z
	DD	0ffffffffH
	DD	imagerel ?sendFileClicked@SendFile@@QEAAXAEAVQString@@AEAHV2@@Z+48
	DD	00H
	DD	imagerel ?sendFileClicked@SendFile@@QEAAXAEAVQString@@AEAHV2@@Z+114
	DD	0ffffffffH
$unwind$?dtor$0@?0??sendFileClicked@SendFile@@QEAAXAEAVQString@@AEAHV2@@Z@4HA DD 020601H
	DD	050023206H
xdata	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
$T1 = 32
_a$ = 40
__$ArrayPad$ = 72
this$ = 96
_t1$ = 104
_t2$ = 112
_t3$ = 120
?sendFileClicked@SendFile@@QEAAXAEAVQString@@AEAHV2@@Z PROC ; SendFile::sendFileClicked
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_sendfile.cpp
; Line 143
$LN4:
	mov	QWORD PTR [rsp+32], r9
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 88					; 00000058H
	mov	QWORD PTR $T1[rsp], -2
	mov	rax, QWORD PTR __security_cookie
	xor	rax, rsp
	mov	QWORD PTR __$ArrayPad$[rsp], rax
; Line 144
	mov	QWORD PTR _a$[rsp], 0
	mov	rax, QWORD PTR _t1$[rsp]
	mov	QWORD PTR _a$[rsp+8], rax
	mov	rax, QWORD PTR _t2$[rsp]
	mov	QWORD PTR _a$[rsp+16], rax
	mov	rax, QWORD PTR _t3$[rsp]
	mov	QWORD PTR _a$[rsp+24], rax
; Line 145
	lea	r9, QWORD PTR _a$[rsp]
	xor	r8d, r8d
	lea	rdx, OFFSET FLAT:?staticMetaObject@SendFile@@2UQMetaObject@@B ; SendFile::staticMetaObject
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?activate@QMetaObject@@SAXPEAVQObject@@PEBU1@HPEAPEAX@Z
	npad	1
; Line 146
	mov	rcx, QWORD PTR _t3$[rsp]
	call	QWORD PTR __imp_??1QString@@QEAA@XZ
	mov	rcx, QWORD PTR __$ArrayPad$[rsp]
	xor	rcx, rsp
	call	__security_check_cookie
	add	rsp, 88					; 00000058H
	ret	0
?sendFileClicked@SendFile@@QEAAXAEAVQString@@AEAHV2@@Z ENDP ; SendFile::sendFileClicked
_TEXT	ENDS
text$x	SEGMENT
$T1 = 32
_a$ = 40
__$ArrayPad$ = 72
this$ = 96
_t1$ = 104
_t2$ = 112
_t3$ = 120
?dtor$0@?0??sendFileClicked@SendFile@@QEAAXAEAVQString@@AEAHV2@@Z@4HA PROC ; `SendFile::sendFileClicked'::`1'::dtor$0
	push	rbp
	sub	rsp, 32					; 00000020H
	mov	rbp, rdx
	mov	rcx, QWORD PTR _t3$[rbp]
	call	QWORD PTR __imp_??1QString@@QEAA@XZ
	add	rsp, 32					; 00000020H
	pop	rbp
	ret	0
?dtor$0@?0??sendFileClicked@SendFile@@QEAAXAEAVQString@@AEAHV2@@Z@4HA ENDP ; `SendFile::sendFileClicked'::`1'::dtor$0
text$x	ENDS
; Function compile flags: /Odtp
text$x	SEGMENT
$T1 = 32
_a$ = 40
__$ArrayPad$ = 72
this$ = 96
_t1$ = 104
_t2$ = 112
_t3$ = 120
?dtor$0@?0??sendFileClicked@SendFile@@QEAAXAEAVQString@@AEAHV2@@Z@4HA PROC ; `SendFile::sendFileClicked'::`1'::dtor$0
	push	rbp
	sub	rsp, 32					; 00000020H
	mov	rbp, rdx
	mov	rcx, QWORD PTR _t3$[rbp]
	call	QWORD PTR __imp_??1QString@@QEAA@XZ
	add	rsp, 32					; 00000020H
	pop	rbp
	ret	0
?dtor$0@?0??sendFileClicked@SendFile@@QEAAXAEAVQString@@AEAHV2@@Z@4HA ENDP ; `SendFile::sendFileClicked'::`1'::dtor$0
text$x	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv69 = 32
tv140 = 36
_t$1 = 40
$T2 = 48
tv143 = 56
result$3 = 64
$T4 = 72
$T5 = 80
_o$ = 112
_c$ = 120
_id$ = 128
_a$ = 136
?qt_static_metacall@SendFile@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; SendFile::qt_static_metacall
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_sendfile.cpp
; Line 83
$LN17:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 104				; 00000068H
; Line 84
	cmp	DWORD PTR _c$[rsp], 0
	jne	$LN4@qt_static_
; Line 85
	mov	rax, QWORD PTR _o$[rsp]
	mov	QWORD PTR _t$1[rsp], rax
; Line 87
	mov	eax, DWORD PTR _id$[rsp]
	mov	DWORD PTR tv69[rsp], eax
	cmp	DWORD PTR tv69[rsp], 0
	je	SHORT $LN6@qt_static_
	cmp	DWORD PTR tv69[rsp], 1
	je	SHORT $LN7@qt_static_
	cmp	DWORD PTR tv69[rsp], 2
	je	SHORT $LN8@qt_static_
	jmp	$LN2@qt_static_
$LN6@qt_static_:
; Line 88
	lea	rax, QWORD PTR $T4[rsp]
	mov	QWORD PTR $T2[rsp], rax
	mov	eax, 8
	imul	rax, rax, 3
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rdx, QWORD PTR [rcx+rax]
	mov	rcx, QWORD PTR $T2[rsp]
	call	QWORD PTR __imp_??0QString@@QEAA@AEBV0@@Z
	mov	QWORD PTR tv143[rsp], rax
	mov	eax, 8
	imul	rax, rax, 2
	mov	ecx, 8
	imul	rcx, rcx, 1
	mov	r9, QWORD PTR tv143[rsp]
	mov	rdx, QWORD PTR _a$[rsp]
	mov	r8, QWORD PTR [rdx+rax]
	mov	rax, QWORD PTR _a$[rsp]
	mov	rdx, QWORD PTR [rax+rcx]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?sendFileClicked@SendFile@@QEAAXAEAVQString@@AEAHV2@@Z ; SendFile::sendFileClicked
	jmp	SHORT $LN2@qt_static_
$LN7@qt_static_:
; Line 89
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?on_openBtn_clicked@SendFile@@AEAAXXZ	; SendFile::on_openBtn_clicked
	jmp	SHORT $LN2@qt_static_
$LN8@qt_static_:
; Line 90
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?on_sendBtn_clicked@SendFile@@AEAAXXZ	; SendFile::on_sendBtn_clicked
$LN2@qt_static_:
; Line 93
	jmp	$LN5@qt_static_
$LN4@qt_static_:
	cmp	DWORD PTR _c$[rsp], 10
	jne	$LN5@qt_static_
; Line 94
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	QWORD PTR result$3[rsp], rax
; Line 97
	lea	rax, OFFSET FLAT:?sendFileClicked@SendFile@@QEAAXAEAVQString@@AEAHV2@@Z ; SendFile::sendFileClicked
	mov	QWORD PTR $T5[rsp], rax
	mov	DWORD PTR $T5[rsp+8], 0
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	rcx, QWORD PTR $T5[rsp]
	cmp	QWORD PTR [rax], rcx
	jne	SHORT $LN14@qt_static_
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	cmp	QWORD PTR [rax], 0
	je	SHORT $LN13@qt_static_
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	ecx, DWORD PTR $T5[rsp+8]
	cmp	DWORD PTR [rax+8], ecx
	jne	SHORT $LN14@qt_static_
$LN13@qt_static_:
	mov	DWORD PTR tv140[rsp], 1
	jmp	SHORT $LN15@qt_static_
$LN14@qt_static_:
	mov	DWORD PTR tv140[rsp], 0
$LN15@qt_static_:
	cmp	DWORD PTR tv140[rsp], 0
	je	SHORT $LN5@qt_static_
; Line 98
	mov	rax, QWORD PTR result$3[rsp]
	mov	DWORD PTR [rax], 0
$LN5@qt_static_:
; Line 103
	add	rsp, 104				; 00000068H
	ret	0
?qt_static_metacall@SendFile@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; SendFile::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@SendFile@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; SendFile::qt_metacall
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_sendfile.cpp
; Line 125
$LN9:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 126
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_metacall@BasicWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; BasicWindow::qt_metacall
	mov	DWORD PTR _id$[rsp], eax
; Line 127
	cmp	DWORD PTR _id$[rsp], 0
	jge	SHORT $LN2@qt_metacal
; Line 128
	mov	eax, DWORD PTR _id$[rsp]
	jmp	SHORT $LN1@qt_metacal
$LN2@qt_metacal:
; Line 129
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN3@qt_metacal
; Line 130
	cmp	DWORD PTR _id$[rsp], 3
	jge	SHORT $LN5@qt_metacal
; Line 131
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_static_metacall@SendFile@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; SendFile::qt_static_metacall
$LN5@qt_metacal:
; Line 132
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 3
	mov	DWORD PTR _id$[rsp], eax
	jmp	SHORT $LN4@qt_metacal
$LN3@qt_metacal:
; Line 133
	cmp	DWORD PTR _c$[rsp], 12
	jne	SHORT $LN6@qt_metacal
; Line 134
	cmp	DWORD PTR _id$[rsp], 3
	jge	SHORT $LN7@qt_metacal
; Line 135
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	DWORD PTR [rax], -1
$LN7@qt_metacal:
; Line 136
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 3
	mov	DWORD PTR _id$[rsp], eax
$LN6@qt_metacal:
$LN4@qt_metacal:
; Line 138
	mov	eax, DWORD PTR _id$[rsp]
$LN1@qt_metacal:
; Line 139
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacall@SendFile@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; SendFile::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_clname$ = 56
?qt_metacast@SendFile@@UEAAPEAXPEBD@Z PROC		; SendFile::qt_metacast
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_sendfile.cpp
; Line 117
$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 118
	cmp	QWORD PTR _clname$[rsp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 119
	lea	rdx, OFFSET FLAT:?qt_meta_stringdata_SendFile@@3Uqt_meta_stringdata_SendFile_t@@B+240
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 120
	mov	rax, QWORD PTR this$[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 121
	mov	rdx, QWORD PTR _clname$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_metacast@BasicWindow@@UEAAPEAXPEBD@Z ; BasicWindow::qt_metacast
$LN1@qt_metacas:
; Line 122
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacast@SendFile@@UEAAPEAXPEBD@Z ENDP		; SendFile::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = 32
this$ = 64
?metaObject@SendFile@@UEBAPEBUQMetaObject@@XZ PROC	; SendFile::metaObject
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_sendfile.cpp
; Line 112
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 113
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	QWORD PTR [rax+40], 0
	je	SHORT $LN3@metaObject
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	rcx, rax
	call	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
	mov	QWORD PTR tv82[rsp], rax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@SendFile@@2UQMetaObject@@B ; SendFile::staticMetaObject
	mov	QWORD PTR tv82[rsp], rax
$LN4@metaObject:
	mov	rax, QWORD PTR tv82[rsp]
; Line 114
	add	rsp, 56					; 00000038H
	ret	0
?metaObject@SendFile@@UEBAPEBUQMetaObject@@XZ ENDP	; SendFile::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File e:\qt\5.9.6\msvc2017_64\include\qtcore\qscopedpointer.h
; Line 117
	mov	QWORD PTR [rsp+8], rcx
; Line 118
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 8
__formal$ = 16
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_sendfile.cpp
; Line 149
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 8
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_sendfile.cpp
; Line 149
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
