; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27048.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	?staticMetaObject@TalkWindowShell@@2UQMetaObject@@B ; TalkWindowShell::staticMetaObject
PUBLIC	?qt_static_metacall@TalkWindowShell@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; TalkWindowShell::qt_static_metacall
EXTRN	?staticMetaObject@BasicWindow@@2UQMetaObject@@B:BYTE ; BasicWindow::staticMetaObject
CONST	SEGMENT
$SG149871 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
$SG138084 DB	00H
	ORG $+12
$SG149872 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG149873 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG151892 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG151893 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG151894 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG152187 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG152188 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG152189 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG152482 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG152483 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG152484 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG153259 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG153260 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG153261 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG153554 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG153555 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG153556 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG153849 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG153850 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG153851 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
?staticMetaObject@TalkWindowShell@@2UQMetaObject@@B DQ FLAT:?staticMetaObject@BasicWindow@@2UQMetaObject@@B ; TalkWindowShell::staticMetaObject
	DQ	FLAT:?qt_meta_stringdata_TalkWindowShell@@3Uqt_meta_stringdata_TalkWindowShell_t@@B
	DQ	FLAT:?qt_meta_data_TalkWindowShell@@3QBIB
	DQ	FLAT:?qt_static_metacall@TalkWindowShell@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
	DQ	0000000000000000H
	DQ	0000000000000000H
$SG154192 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG154193 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG154194 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
?qt_meta_stringdata_TalkWindowShell@@3Uqt_meta_stringdata_TalkWindowShell_t@@B DD 0ffffffffH ; qt_meta_stringdata_TalkWindowShell
	DD	0fH
	DD	00H
	ORG $+4
	DQ	0000000000000168H
	DD	0ffffffffH
	DD	013H
	DD	00H
	ORG $+4
	DQ	0000000000000160H
	DD	0ffffffffH
	DD	00H
	DD	00H
	ORG $+4
	DQ	000000000000015cH
	DD	0ffffffffH
	DD	010H
	DD	00H
	ORG $+4
	DQ	0000000000000145H
	DD	0ffffffffH
	DD	08H
	DD	00H
	ORG $+4
	DQ	000000000000013eH
	DD	0ffffffffH
	DD	07H
	DD	00H
	ORG $+4
	DQ	000000000000012fH
	DD	0ffffffffH
	DD	04H
	DD	00H
	ORG $+4
	DQ	000000000000011fH
	DD	0ffffffffH
	DD	07H
	DD	00H
	ORG $+4
	DQ	000000000000010cH
	DD	0ffffffffH
	DD	08H
	DD	00H
	ORG $+4
	DQ	00000000000000fcH
	DD	0ffffffffH
	DD	017H
	DD	00H
	ORG $+4
	DQ	00000000000000edH
	DD	0ffffffffH
	DD	010H
	DD	00H
	ORG $+4
	DQ	00000000000000edH
	DD	0ffffffffH
	DD	04H
	DD	00H
	ORG $+4
	DQ	00000000000000e6H
	DD	0ffffffffH
	DD	014H
	DD	00H
	ORG $+4
	DQ	00000000000000d3H
	DD	0ffffffffH
	DD	0aH
	DD	00H
	ORG $+4
	DQ	00000000000000d0H
	DD	0ffffffffH
	DD	012H
	DD	00H
	ORG $+4
	DQ	00000000000000c3H
	DB	054H
	DB	061H
	DB	06cH
	DB	06bH
	DB	057H
	DB	069H
	DB	06eH
	DB	064H
	DB	06fH
	DB	077H
	DB	053H
	DB	068H
	DB	065H
	DB	06cH
	DB	06cH
	DB	00H
	DB	06fH
	DB	06eH
	DB	045H
	DB	06dH
	DB	06fH
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	042H
	DB	074H
	DB	06eH
	DB	043H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	00H
	DB	00H
	DB	075H
	DB	070H
	DB	064H
	DB	061H
	DB	074H
	DB	065H
	DB	053H
	DB	065H
	DB	06eH
	DB	064H
	DB	054H
	DB	063H
	DB	070H
	DB	04dH
	DB	073H
	DB	067H
	DB	00H
	DB	051H
	DB	053H
	DB	074H
	DB	072H
	DB	069H
	DB	06eH
	DB	067H
	DB	026H
	DB	00H
	DB	073H
	DB	074H
	DB	072H
	DB	044H
	DB	061H
	DB	074H
	DB	061H
	DB	00H
	DB	069H
	DB	06eH
	DB	074H
	DB	026H
	DB	00H
	DB	06dH
	DB	073H
	DB	067H
	DB	054H
	DB	079H
	DB	070H
	DB	065H
	DB	00H
	DB	066H
	DB	069H
	DB	06cH
	DB	065H
	DB	04eH
	DB	061H
	DB	06dH
	DB	065H
	DB	00H
	DB	06fH
	DB	06eH
	DB	054H
	DB	061H
	DB	06cH
	DB	06bH
	DB	057H
	DB	069H
	DB	06eH
	DB	064H
	DB	06fH
	DB	077H
	DB	049H
	DB	074H
	DB	065H
	DB	06dH
	DB	043H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	00H
	DB	051H
	DB	04cH
	DB	069H
	DB	073H
	DB	074H
	DB	057H
	DB	069H
	DB	064H
	DB	067H
	DB	065H
	DB	074H
	DB	049H
	DB	074H
	DB	065H
	DB	06dH
	DB	02aH
	DB	00H
	DB	069H
	DB	074H
	DB	065H
	DB	06dH
	DB	00H
	DB	06fH
	DB	06eH
	DB	045H
	DB	06dH
	DB	06fH
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	049H
	DB	074H
	DB	065H
	DB	06dH
	DB	043H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	00H
	DB	065H
	DB	06dH
	DB	06fH
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	04eH
	DB	075H
	DB	06dH
	DB	00H
	DB	070H
	DB	072H
	DB	06fH
	DB	063H
	DB	065H
	DB	073H
	DB	073H
	DB	050H
	DB	065H
	DB	06eH
	DB	064H
	DB	069H
	DB	06eH
	DB	067H
	DB	044H
	DB	061H
	DB	074H
	DB	061H
	DB	00H
	ORG $+2
	ORG $+8
?qt_meta_data_TalkWindowShell@@3QBIB DD 07H		; qt_meta_data_TalkWindowShell
	DD	00H
	DD	00H
	DD	00H
	DD	06H
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	01H
	DD	02cH
	DD	02H
	DD	0aH
	DD	03H
	DD	03H
	DD	02fH
	DD	02H
	DD	0aH
	DD	03H
	DD	02H
	DD	036H
	DD	02H
	DD	02aH
	DD	09H
	DD	01H
	DD	03bH
	DD	02H
	DD	08H
	DD	0cH
	DD	01H
	DD	03eH
	DD	02H
	DD	08H
	DD	0eH
	DD	00H
	DD	041H
	DD	02H
	DD	08H
	DD	02bH
	DD	01H
	DD	02H
	DD	02bH
	DD	080000004H
	DD	080000006H
	DD	0aH
	DD	05H
	DD	07H
	DD	08H
	DD	02bH
	DD	080000004H
	DD	080000006H
	DD	05H
	DD	07H
	DD	02bH
	DD	08000000aH
	DD	0bH
	DD	02bH
	DD	02H
	DD	0dH
	DD	02bH
	DD	00H
	ORG $+4
$SG154535 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG154536 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG154537 DB	'qRegisterNormalizedMetaType', 00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@TalkWindowShell@@UEBAPEBUQMetaObject@@XZ ; TalkWindowShell::metaObject
PUBLIC	?qt_metacast@TalkWindowShell@@UEAAPEAXPEBD@Z	; TalkWindowShell::qt_metacast
PUBLIC	?qt_metacall@TalkWindowShell@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; TalkWindowShell::qt_metacall
EXTRN	strcmp:PROC
EXTRN	__imp_??0QString@@QEAA@AEBV0@@Z:PROC
EXTRN	__imp_??0QString@@QEAA@PEBD@Z:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	?qt_metacast@BasicWindow@@UEAAPEAXPEBD@Z:PROC	; BasicWindow::qt_metacast
EXTRN	?qt_metacall@BasicWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC ; BasicWindow::qt_metacall
EXTRN	?onEmotionBtnClicked@TalkWindowShell@@QEAAX_N@Z:PROC ; TalkWindowShell::onEmotionBtnClicked
EXTRN	?updateSendTcpMsg@TalkWindowShell@@QEAAXAEAVQString@@AEAHV2@@Z:PROC ; TalkWindowShell::updateSendTcpMsg
EXTRN	?onTalkWindowItemClicked@TalkWindowShell@@AEAAXPEAVQListWidgetItem@@@Z:PROC ; TalkWindowShell::onTalkWindowItemClicked
EXTRN	?onEmotionItemClicked@TalkWindowShell@@AEAAXH@Z:PROC ; TalkWindowShell::onEmotionItemClicked
EXTRN	?processPendingData@TalkWindowShell@@AEAAXXZ:PROC ; TalkWindowShell::processPendingData
EXTRN	__ImageBase:BYTE
pdata	SEGMENT
$pdata$?metaObject@TalkWindowShell@@UEBAPEBUQMetaObject@@XZ DD imagerel $LN5
	DD	imagerel $LN5+88
	DD	imagerel $unwind$?metaObject@TalkWindowShell@@UEBAPEBUQMetaObject@@XZ
$pdata$?qt_metacast@TalkWindowShell@@UEAAPEAXPEBD@Z DD imagerel $LN5
	DD	imagerel $LN5+74
	DD	imagerel $unwind$?qt_metacast@TalkWindowShell@@UEAAPEAXPEBD@Z
$pdata$?qt_metacall@TalkWindowShell@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN9
	DD	imagerel $LN9+173
	DD	imagerel $unwind$?qt_metacall@TalkWindowShell@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?qt_static_metacall@TalkWindowShell@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN16
	DD	imagerel $LN16+440
	DD	imagerel $unwind$?qt_static_metacall@TalkWindowShell@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
pdata	ENDS
xdata	SEGMENT
$unwind$?metaObject@TalkWindowShell@@UEBAPEBUQMetaObject@@XZ DD 010901H
	DD	06209H
$unwind$?qt_metacast@TalkWindowShell@@UEAAPEAXPEBD@Z DD 010e01H
	DD	0420eH
$unwind$?qt_metacall@TalkWindowShell@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	04217H
$unwind$?qt_static_metacall@TalkWindowShell@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	0c217H
xdata	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv69 = 32
_t$1 = 40
$T2 = 48
tv154 = 56
$T3 = 64
tv156 = 72
$T4 = 80
$T5 = 88
_o$ = 112
_c$ = 120
_id$ = 128
_a$ = 136
?qt_static_metacall@TalkWindowShell@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; TalkWindowShell::qt_static_metacall
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_talkwindowshell.cpp
; Line 92
$LN16:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 104				; 00000068H
; Line 93
	cmp	DWORD PTR _c$[rsp], 0
	jne	$LN4@qt_static_
; Line 94
	mov	rax, QWORD PTR _o$[rsp]
	mov	QWORD PTR _t$1[rsp], rax
; Line 96
	mov	eax, DWORD PTR _id$[rsp]
	mov	DWORD PTR tv69[rsp], eax
	cmp	DWORD PTR tv69[rsp], 5
	ja	$LN4@qt_static_
	movsxd	rax, DWORD PTR tv69[rsp]
	lea	rcx, OFFSET FLAT:__ImageBase
	mov	eax, DWORD PTR $LN15@qt_static_[rcx+rax*4]
	add	rax, rcx
	jmp	rax
$LN5@qt_static_:
; Line 97
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	movzx	edx, BYTE PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?onEmotionBtnClicked@TalkWindowShell@@QEAAX_N@Z ; TalkWindowShell::onEmotionBtnClicked
	jmp	$LN4@qt_static_
$LN6@qt_static_:
; Line 98
	lea	rax, QWORD PTR $T4[rsp]
	mov	QWORD PTR $T2[rsp], rax
	mov	eax, 8
	imul	rax, rax, 3
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rdx, QWORD PTR [rcx+rax]
	mov	rcx, QWORD PTR $T2[rsp]
	call	QWORD PTR __imp_??0QString@@QEAA@AEBV0@@Z
	mov	QWORD PTR tv154[rsp], rax
	mov	eax, 8
	imul	rax, rax, 2
	mov	ecx, 8
	imul	rcx, rcx, 1
	mov	r9, QWORD PTR tv154[rsp]
	mov	rdx, QWORD PTR _a$[rsp]
	mov	r8, QWORD PTR [rdx+rax]
	mov	rax, QWORD PTR _a$[rsp]
	mov	rdx, QWORD PTR [rax+rcx]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?updateSendTcpMsg@TalkWindowShell@@QEAAXAEAVQString@@AEAHV2@@Z ; TalkWindowShell::updateSendTcpMsg
	jmp	$LN4@qt_static_
$LN7@qt_static_:
; Line 99
	lea	rax, QWORD PTR $T5[rsp]
	mov	QWORD PTR $T3[rsp], rax
	lea	rdx, OFFSET FLAT:$SG138084
	mov	rcx, QWORD PTR $T3[rsp]
	call	QWORD PTR __imp_??0QString@@QEAA@PEBD@Z
	mov	QWORD PTR tv156[rsp], rax
	mov	eax, 8
	imul	rax, rax, 2
	mov	ecx, 8
	imul	rcx, rcx, 1
	mov	r9, QWORD PTR tv156[rsp]
	mov	rdx, QWORD PTR _a$[rsp]
	mov	r8, QWORD PTR [rdx+rax]
	mov	rax, QWORD PTR _a$[rsp]
	mov	rdx, QWORD PTR [rax+rcx]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?updateSendTcpMsg@TalkWindowShell@@QEAAXAEAVQString@@AEAHV2@@Z ; TalkWindowShell::updateSendTcpMsg
	jmp	SHORT $LN4@qt_static_
$LN8@qt_static_:
; Line 100
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	rdx, QWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?onTalkWindowItemClicked@TalkWindowShell@@AEAAXPEAVQListWidgetItem@@@Z ; TalkWindowShell::onTalkWindowItemClicked
	jmp	SHORT $LN4@qt_static_
$LN9@qt_static_:
; Line 101
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?onEmotionItemClicked@TalkWindowShell@@AEAAXH@Z ; TalkWindowShell::onEmotionItemClicked
	jmp	SHORT $LN4@qt_static_
$LN10@qt_static_:
; Line 102
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?processPendingData@TalkWindowShell@@AEAAXXZ ; TalkWindowShell::processPendingData
$LN4@qt_static_:
; Line 106
	add	rsp, 104				; 00000068H
	ret	0
$LN15@qt_static_:
	DD	$LN5@qt_static_
	DD	$LN6@qt_static_
	DD	$LN7@qt_static_
	DD	$LN8@qt_static_
	DD	$LN9@qt_static_
	DD	$LN10@qt_static_
?qt_static_metacall@TalkWindowShell@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; TalkWindowShell::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@TalkWindowShell@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; TalkWindowShell::qt_metacall
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_talkwindowshell.cpp
; Line 128
$LN9:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 129
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_metacall@BasicWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; BasicWindow::qt_metacall
	mov	DWORD PTR _id$[rsp], eax
; Line 130
	cmp	DWORD PTR _id$[rsp], 0
	jge	SHORT $LN2@qt_metacal
; Line 131
	mov	eax, DWORD PTR _id$[rsp]
	jmp	SHORT $LN1@qt_metacal
$LN2@qt_metacal:
; Line 132
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN3@qt_metacal
; Line 133
	cmp	DWORD PTR _id$[rsp], 6
	jge	SHORT $LN5@qt_metacal
; Line 134
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_static_metacall@TalkWindowShell@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; TalkWindowShell::qt_static_metacall
$LN5@qt_metacal:
; Line 135
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 6
	mov	DWORD PTR _id$[rsp], eax
	jmp	SHORT $LN4@qt_metacal
$LN3@qt_metacal:
; Line 136
	cmp	DWORD PTR _c$[rsp], 12
	jne	SHORT $LN6@qt_metacal
; Line 137
	cmp	DWORD PTR _id$[rsp], 6
	jge	SHORT $LN7@qt_metacal
; Line 138
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	DWORD PTR [rax], -1
$LN7@qt_metacal:
; Line 139
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 6
	mov	DWORD PTR _id$[rsp], eax
$LN6@qt_metacal:
$LN4@qt_metacal:
; Line 141
	mov	eax, DWORD PTR _id$[rsp]
$LN1@qt_metacal:
; Line 142
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacall@TalkWindowShell@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; TalkWindowShell::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_clname$ = 56
?qt_metacast@TalkWindowShell@@UEAAPEAXPEBD@Z PROC	; TalkWindowShell::qt_metacast
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_talkwindowshell.cpp
; Line 120
$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 121
	cmp	QWORD PTR _clname$[rsp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 122
	lea	rdx, OFFSET FLAT:?qt_meta_stringdata_TalkWindowShell@@3Uqt_meta_stringdata_TalkWindowShell_t@@B+360
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 123
	mov	rax, QWORD PTR this$[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 124
	mov	rdx, QWORD PTR _clname$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_metacast@BasicWindow@@UEAAPEAXPEBD@Z ; BasicWindow::qt_metacast
$LN1@qt_metacas:
; Line 125
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacast@TalkWindowShell@@UEAAPEAXPEBD@Z ENDP	; TalkWindowShell::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = 32
this$ = 64
?metaObject@TalkWindowShell@@UEBAPEBUQMetaObject@@XZ PROC ; TalkWindowShell::metaObject
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_talkwindowshell.cpp
; Line 115
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 116
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	QWORD PTR [rax+40], 0
	je	SHORT $LN3@metaObject
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	rcx, rax
	call	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
	mov	QWORD PTR tv82[rsp], rax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@TalkWindowShell@@2UQMetaObject@@B ; TalkWindowShell::staticMetaObject
	mov	QWORD PTR tv82[rsp], rax
$LN4@metaObject:
	mov	rax, QWORD PTR tv82[rsp]
; Line 117
	add	rsp, 56					; 00000038H
	ret	0
?metaObject@TalkWindowShell@@UEBAPEBUQMetaObject@@XZ ENDP ; TalkWindowShell::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File e:\qt\5.9.6\msvc2017_64\include\qtcore\qscopedpointer.h
; Line 117
	mov	QWORD PTR [rsp+8], rcx
; Line 118
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 8
__formal$ = 16
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_talkwindowshell.cpp
; Line 145
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 8
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_talkwindowshell.cpp
; Line 145
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
