; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27048.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG125383 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG125384 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG125385 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG125678 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG125679 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG125680 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG125973 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG125974 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG125975 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
?qt_meta_stringdata_QClickLabel@@3Uqt_meta_stringdata_QClickLabel_t@@B DD 0ffffffffH ; qt_meta_stringdata_QClickLabel
	DD	0bH
	DD	00H
	ORG $+4
	DQ	0000000000000048H
	DD	0ffffffffH
	DD	07H
	DD	00H
	ORG $+4
	DQ	000000000000003cH
	DD	0ffffffffH
	DD	00H
	DD	00H
	ORG $+4
	DQ	000000000000002cH
	DB	051H
	DB	043H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	04cH
	DB	061H
	DB	062H
	DB	065H
	DB	06cH
	DB	00H
	DB	063H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	00H
	DB	00H
	ORG $+3
?qt_meta_data_QClickLabel@@3QBIB DD 07H			; qt_meta_data_QClickLabel
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	01H
	DD	00H
	DD	013H
	DD	02H
	DD	06H
	DD	02bH
	DD	00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@QClickLabel@@UEBAPEBUQMetaObject@@XZ ; QClickLabel::metaObject
PUBLIC	?qt_metacast@QClickLabel@@UEAAPEAXPEBD@Z	; QClickLabel::qt_metacast
PUBLIC	?qt_metacall@QClickLabel@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; QClickLabel::qt_metacall
PUBLIC	?qt_static_metacall@QClickLabel@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; QClickLabel::qt_static_metacall
PUBLIC	?clicked@QClickLabel@@QEAAXXZ			; QClickLabel::clicked
PUBLIC	?staticMetaObject@QClickLabel@@2UQMetaObject@@B	; QClickLabel::staticMetaObject
EXTRN	strcmp:PROC
EXTRN	__imp_?activate@QMetaObject@@SAXPEAVQObject@@PEBU1@HPEAPEAX@Z:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QLabel@@UEAAPEAXPEBD@Z:PROC
EXTRN	__imp_?qt_metacall@QLabel@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC
EXTRN	__imp_?staticMetaObject@QLabel@@2UQMetaObject@@B:BYTE
_BSS	SEGMENT
?staticMetaObject@QClickLabel@@2UQMetaObject@@B DB 030H DUP (?) ; QClickLabel::staticMetaObject
_BSS	ENDS
pdata	SEGMENT
$pdata$?metaObject@QClickLabel@@UEBAPEBUQMetaObject@@XZ DD imagerel $LN5
	DD	imagerel $LN5+88
	DD	imagerel $unwind$?metaObject@QClickLabel@@UEBAPEBUQMetaObject@@XZ
$pdata$?qt_metacast@QClickLabel@@UEAAPEAXPEBD@Z DD imagerel $LN5
	DD	imagerel $LN5+75
	DD	imagerel $unwind$?qt_metacast@QClickLabel@@UEAAPEAXPEBD@Z
$pdata$?qt_metacall@QClickLabel@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN9
	DD	imagerel $LN9+172
	DD	imagerel $unwind$?qt_metacall@QClickLabel@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?qt_static_metacall@QClickLabel@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN14
	DD	imagerel $LN14+246
	DD	imagerel $unwind$?qt_static_metacall@QClickLabel@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?clicked@QClickLabel@@QEAAXXZ DD imagerel $LN3
	DD	imagerel $LN3+38
	DD	imagerel $unwind$?clicked@QClickLabel@@QEAAXXZ
pdata	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@QClickLabel@@2P6AXXZEA@@3P6AXXZEA DQ FLAT:??__E?staticMetaObject@QClickLabel@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@QClickLabel@@2P6AXXZEA@@3P6AXXZEA
CRT$XCU	ENDS
xdata	SEGMENT
$unwind$?metaObject@QClickLabel@@UEBAPEBUQMetaObject@@XZ DD 010901H
	DD	06209H
$unwind$?qt_metacast@QClickLabel@@UEAAPEAXPEBD@Z DD 010e01H
	DD	0420eH
$unwind$?qt_metacall@QClickLabel@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	04217H
$unwind$?qt_static_metacall@QClickLabel@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	0a217H
$unwind$?clicked@QClickLabel@@QEAAXXZ DD 010901H
	DD	04209H
xdata	ENDS
; Function compile flags: /Odtp
;	COMDAT ??__E?staticMetaObject@QClickLabel@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@QClickLabel@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'QClickLabel::staticMetaObject'', COMDAT
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_qclicklabel.cpp
; Line 88
	mov	rax, QWORD PTR __imp_?staticMetaObject@QLabel@@2UQMetaObject@@B
	mov	QWORD PTR ?staticMetaObject@QClickLabel@@2UQMetaObject@@B, rax
	lea	rax, OFFSET FLAT:?qt_meta_stringdata_QClickLabel@@3Uqt_meta_stringdata_QClickLabel_t@@B
	mov	QWORD PTR ?staticMetaObject@QClickLabel@@2UQMetaObject@@B+8, rax
; Line 89
	lea	rax, OFFSET FLAT:?qt_meta_data_QClickLabel@@3QBIB
	mov	QWORD PTR ?staticMetaObject@QClickLabel@@2UQMetaObject@@B+16, rax
	lea	rax, OFFSET FLAT:?qt_static_metacall@QClickLabel@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; QClickLabel::qt_static_metacall
	mov	QWORD PTR ?staticMetaObject@QClickLabel@@2UQMetaObject@@B+24, rax
	mov	QWORD PTR ?staticMetaObject@QClickLabel@@2UQMetaObject@@B+32, 0
	mov	QWORD PTR ?staticMetaObject@QClickLabel@@2UQMetaObject@@B+40, 0
	ret	0
??__E?staticMetaObject@QClickLabel@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'QClickLabel::staticMetaObject''
text$di	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
?clicked@QClickLabel@@QEAAXXZ PROC			; QClickLabel::clicked
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_qclicklabel.cpp
; Line 125
$LN3:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 126
	xor	r9d, r9d
	xor	r8d, r8d
	lea	rdx, OFFSET FLAT:?staticMetaObject@QClickLabel@@2UQMetaObject@@B ; QClickLabel::staticMetaObject
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?activate@QMetaObject@@SAXPEAVQObject@@PEBU1@HPEAPEAX@Z
; Line 127
	add	rsp, 40					; 00000028H
	ret	0
?clicked@QClickLabel@@QEAAXXZ ENDP			; QClickLabel::clicked
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv87 = 32
tv69 = 36
_t$1 = 40
result$2 = 48
$T3 = 56
_o$ = 96
_c$ = 104
_id$ = 112
_a$ = 120
?qt_static_metacall@QClickLabel@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; QClickLabel::qt_static_metacall
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_qclicklabel.cpp
; Line 66
$LN14:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 88					; 00000058H
; Line 67
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN4@qt_static_
; Line 68
	mov	rax, QWORD PTR _o$[rsp]
	mov	QWORD PTR _t$1[rsp], rax
; Line 70
	mov	eax, DWORD PTR _id$[rsp]
	mov	DWORD PTR tv69[rsp], eax
	cmp	DWORD PTR tv69[rsp], 0
	je	SHORT $LN6@qt_static_
	jmp	SHORT $LN7@qt_static_
$LN6@qt_static_:
; Line 71
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?clicked@QClickLabel@@QEAAXXZ		; QClickLabel::clicked
$LN7@qt_static_:
; Line 74
	jmp	$LN5@qt_static_
$LN4@qt_static_:
	cmp	DWORD PTR _c$[rsp], 10
	jne	$LN8@qt_static_
; Line 75
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	QWORD PTR result$2[rsp], rax
; Line 78
	lea	rax, OFFSET FLAT:?clicked@QClickLabel@@QEAAXXZ ; QClickLabel::clicked
	mov	QWORD PTR $T3[rsp], rax
	mov	DWORD PTR $T3[rsp+8], 0
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	rcx, QWORD PTR $T3[rsp]
	cmp	QWORD PTR [rax], rcx
	jne	SHORT $LN12@qt_static_
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	cmp	QWORD PTR [rax], 0
	je	SHORT $LN11@qt_static_
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	ecx, DWORD PTR $T3[rsp+8]
	cmp	DWORD PTR [rax+8], ecx
	jne	SHORT $LN12@qt_static_
$LN11@qt_static_:
	mov	DWORD PTR tv87[rsp], 1
	jmp	SHORT $LN13@qt_static_
$LN12@qt_static_:
	mov	DWORD PTR tv87[rsp], 0
$LN13@qt_static_:
	cmp	DWORD PTR tv87[rsp], 0
	je	SHORT $LN9@qt_static_
; Line 79
	mov	rax, QWORD PTR result$2[rsp]
	mov	DWORD PTR [rax], 0
$LN9@qt_static_:
$LN8@qt_static_:
$LN5@qt_static_:
; Line 85
	add	rsp, 88					; 00000058H
	ret	0
?qt_static_metacall@QClickLabel@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; QClickLabel::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@QClickLabel@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; QClickLabel::qt_metacall
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_qclicklabel.cpp
; Line 107
$LN9:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 108
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacall@QLabel@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
	mov	DWORD PTR _id$[rsp], eax
; Line 109
	cmp	DWORD PTR _id$[rsp], 0
	jge	SHORT $LN2@qt_metacal
; Line 110
	mov	eax, DWORD PTR _id$[rsp]
	jmp	SHORT $LN1@qt_metacal
$LN2@qt_metacal:
; Line 111
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN3@qt_metacal
; Line 112
	cmp	DWORD PTR _id$[rsp], 1
	jge	SHORT $LN5@qt_metacal
; Line 113
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_static_metacall@QClickLabel@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; QClickLabel::qt_static_metacall
$LN5@qt_metacal:
; Line 114
	mov	eax, DWORD PTR _id$[rsp]
	dec	eax
	mov	DWORD PTR _id$[rsp], eax
	jmp	SHORT $LN4@qt_metacal
$LN3@qt_metacal:
; Line 115
	cmp	DWORD PTR _c$[rsp], 12
	jne	SHORT $LN6@qt_metacal
; Line 116
	cmp	DWORD PTR _id$[rsp], 1
	jge	SHORT $LN7@qt_metacal
; Line 117
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	DWORD PTR [rax], -1
$LN7@qt_metacal:
; Line 118
	mov	eax, DWORD PTR _id$[rsp]
	dec	eax
	mov	DWORD PTR _id$[rsp], eax
$LN6@qt_metacal:
$LN4@qt_metacal:
; Line 120
	mov	eax, DWORD PTR _id$[rsp]
$LN1@qt_metacal:
; Line 121
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacall@QClickLabel@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; QClickLabel::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_clname$ = 56
?qt_metacast@QClickLabel@@UEAAPEAXPEBD@Z PROC		; QClickLabel::qt_metacast
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_qclicklabel.cpp
; Line 99
$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 100
	cmp	QWORD PTR _clname$[rsp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 101
	lea	rdx, OFFSET FLAT:?qt_meta_stringdata_QClickLabel@@3Uqt_meta_stringdata_QClickLabel_t@@B+72
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 102
	mov	rax, QWORD PTR this$[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 103
	mov	rdx, QWORD PTR _clname$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacast@QLabel@@UEAAPEAXPEBD@Z
$LN1@qt_metacas:
; Line 104
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacast@QClickLabel@@UEAAPEAXPEBD@Z ENDP		; QClickLabel::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = 32
this$ = 64
?metaObject@QClickLabel@@UEBAPEBUQMetaObject@@XZ PROC	; QClickLabel::metaObject
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_qclicklabel.cpp
; Line 94
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 95
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	QWORD PTR [rax+40], 0
	je	SHORT $LN3@metaObject
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	rcx, rax
	call	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
	mov	QWORD PTR tv82[rsp], rax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@QClickLabel@@2UQMetaObject@@B ; QClickLabel::staticMetaObject
	mov	QWORD PTR tv82[rsp], rax
$LN4@metaObject:
	mov	rax, QWORD PTR tv82[rsp]
; Line 96
	add	rsp, 56					; 00000038H
	ret	0
?metaObject@QClickLabel@@UEBAPEBUQMetaObject@@XZ ENDP	; QClickLabel::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File e:\qt\5.9.6\msvc2017_64\include\qtcore\qscopedpointer.h
; Line 117
	mov	QWORD PTR [rsp+8], rcx
; Line 118
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 8
__formal$ = 16
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_qclicklabel.cpp
; Line 130
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 8
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_qclicklabel.cpp
; Line 130
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
