; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27048.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG131805 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG131806 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG131807 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG132100 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG132101 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG132102 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG132395 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG132396 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG132397 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
?qt_meta_stringdata_RootContatItem@@3Uqt_meta_stringdata_RootContatItem_t@@B DD 0ffffffffH ; qt_meta_stringdata_RootContatItem
	DD	0eH
	DD	00H
	ORG $+4
	DQ	0000000000000030H
	DD	0ffffffffH
	DD	08H
	DD	00H
	ORG $+4
	DQ	0000000000000027H
	DB	052H
	DB	06fH
	DB	06fH
	DB	074H
	DB	043H
	DB	06fH
	DB	06eH
	DB	074H
	DB	061H
	DB	074H
	DB	049H
	DB	074H
	DB	065H
	DB	06dH
	DB	00H
	DB	072H
	DB	06fH
	DB	074H
	DB	061H
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	00H
	ORG $+8
?qt_meta_data_RootContatItem@@3QBIB DD 07H		; qt_meta_data_RootContatItem
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	02H
	DD	095103H
	DD	00H
$SG129931 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+5
$SG129932 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG129933 DB	'qRegisterNormalizedMetaType', 00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@RootContatItem@@UEBAPEBUQMetaObject@@XZ ; RootContatItem::metaObject
PUBLIC	?qt_metacast@RootContatItem@@UEAAPEAXPEBD@Z	; RootContatItem::qt_metacast
PUBLIC	?qt_metacall@RootContatItem@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; RootContatItem::qt_metacall
PUBLIC	?qt_static_metacall@RootContatItem@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; RootContatItem::qt_static_metacall
PUBLIC	?staticMetaObject@RootContatItem@@2UQMetaObject@@B ; RootContatItem::staticMetaObject
EXTRN	strcmp:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QLabel@@UEAAPEAXPEBD@Z:PROC
EXTRN	__imp_?qt_metacall@QLabel@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC
EXTRN	?rotation@RootContatItem@@AEAAHXZ:PROC		; RootContatItem::rotation
EXTRN	?setRotation@RootContatItem@@AEAAXH@Z:PROC	; RootContatItem::setRotation
EXTRN	__imp_?staticMetaObject@QLabel@@2UQMetaObject@@B:BYTE
_BSS	SEGMENT
?staticMetaObject@RootContatItem@@2UQMetaObject@@B DB 030H DUP (?) ; RootContatItem::staticMetaObject
_BSS	ENDS
pdata	SEGMENT
$pdata$?metaObject@RootContatItem@@UEBAPEBUQMetaObject@@XZ DD imagerel $LN5
	DD	imagerel $LN5+88
	DD	imagerel $unwind$?metaObject@RootContatItem@@UEBAPEBUQMetaObject@@XZ
$pdata$?qt_metacast@RootContatItem@@UEAAPEAXPEBD@Z DD imagerel $LN5
	DD	imagerel $LN5+75
	DD	imagerel $unwind$?qt_metacast@RootContatItem@@UEAAPEAXPEBD@Z
$pdata$?qt_metacall@RootContatItem@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN16
	DD	imagerel $LN16+234
	DD	imagerel $unwind$?qt_metacall@RootContatItem@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?qt_static_metacall@RootContatItem@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN16
	DD	imagerel $LN16+178
	DD	imagerel $unwind$?qt_static_metacall@RootContatItem@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
pdata	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@RootContatItem@@2P6AXXZEA@@3P6AXXZEA DQ FLAT:??__E?staticMetaObject@RootContatItem@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@RootContatItem@@2P6AXXZEA@@3P6AXXZEA
CRT$XCU	ENDS
xdata	SEGMENT
$unwind$?metaObject@RootContatItem@@UEBAPEBUQMetaObject@@XZ DD 010901H
	DD	06209H
$unwind$?qt_metacast@RootContatItem@@UEAAPEAXPEBD@Z DD 010e01H
	DD	0420eH
$unwind$?qt_metacall@RootContatItem@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	04217H
$unwind$?qt_static_metacall@RootContatItem@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	0a217H
xdata	ENDS
; Function compile flags: /Odtp
;	COMDAT ??__E?staticMetaObject@RootContatItem@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@RootContatItem@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'RootContatItem::staticMetaObject'', COMDAT
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_rootcontatitem.cpp
; Line 91
	mov	rax, QWORD PTR __imp_?staticMetaObject@QLabel@@2UQMetaObject@@B
	mov	QWORD PTR ?staticMetaObject@RootContatItem@@2UQMetaObject@@B, rax
	lea	rax, OFFSET FLAT:?qt_meta_stringdata_RootContatItem@@3Uqt_meta_stringdata_RootContatItem_t@@B
	mov	QWORD PTR ?staticMetaObject@RootContatItem@@2UQMetaObject@@B+8, rax
; Line 92
	lea	rax, OFFSET FLAT:?qt_meta_data_RootContatItem@@3QBIB
	mov	QWORD PTR ?staticMetaObject@RootContatItem@@2UQMetaObject@@B+16, rax
	lea	rax, OFFSET FLAT:?qt_static_metacall@RootContatItem@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; RootContatItem::qt_static_metacall
	mov	QWORD PTR ?staticMetaObject@RootContatItem@@2UQMetaObject@@B+24, rax
	mov	QWORD PTR ?staticMetaObject@RootContatItem@@2UQMetaObject@@B+32, 0
	mov	QWORD PTR ?staticMetaObject@RootContatItem@@2UQMetaObject@@B+40, 0
	ret	0
??__E?staticMetaObject@RootContatItem@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'RootContatItem::staticMetaObject''
text$di	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv71 = 32
tv82 = 36
_t$1 = 40
_v$2 = 48
_v$3 = 56
_t$4 = 64
_o$ = 96
_c$ = 104
_id$ = 112
_a$ = 120
?qt_static_metacall@RootContatItem@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; RootContatItem::qt_static_metacall
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_rootcontatitem.cpp
; Line 62
$LN16:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 88					; 00000058H
; Line 65
	cmp	DWORD PTR _c$[rsp], 1
	jne	SHORT $LN6@qt_static_
; Line 66
	mov	rax, QWORD PTR _o$[rsp]
	mov	QWORD PTR _t$1[rsp], rax
; Line 68
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	QWORD PTR _v$2[rsp], rax
; Line 69
	mov	eax, DWORD PTR _id$[rsp]
	mov	DWORD PTR tv71[rsp], eax
	cmp	DWORD PTR tv71[rsp], 0
	je	SHORT $LN8@qt_static_
	jmp	SHORT $LN9@qt_static_
$LN8@qt_static_:
; Line 70
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?rotation@RootContatItem@@AEAAHXZ	; RootContatItem::rotation
	mov	rcx, QWORD PTR _v$2[rsp]
	mov	DWORD PTR [rcx], eax
$LN9@qt_static_:
; Line 73
	jmp	SHORT $LN7@qt_static_
$LN6@qt_static_:
	cmp	DWORD PTR _c$[rsp], 2
	jne	SHORT $LN10@qt_static_
; Line 74
	mov	rax, QWORD PTR _o$[rsp]
	mov	QWORD PTR _t$4[rsp], rax
; Line 76
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	QWORD PTR _v$3[rsp], rax
; Line 77
	mov	eax, DWORD PTR _id$[rsp]
	mov	DWORD PTR tv82[rsp], eax
	cmp	DWORD PTR tv82[rsp], 0
	je	SHORT $LN12@qt_static_
	jmp	SHORT $LN13@qt_static_
$LN12@qt_static_:
; Line 78
	mov	rax, QWORD PTR _v$3[rsp]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$4[rsp]
	call	?setRotation@RootContatItem@@AEAAXH@Z	; RootContatItem::setRotation
$LN13@qt_static_:
$LN10@qt_static_:
$LN7@qt_static_:
; Line 88
	add	rsp, 88					; 00000058H
	ret	0
?qt_static_metacall@RootContatItem@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; RootContatItem::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@RootContatItem@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; RootContatItem::qt_metacall
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_rootcontatitem.cpp
; Line 110
$LN16:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 111
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacall@QLabel@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
	mov	DWORD PTR _id$[rsp], eax
; Line 112
	cmp	DWORD PTR _id$[rsp], 0
	jge	SHORT $LN2@qt_metacal
; Line 113
	mov	eax, DWORD PTR _id$[rsp]
	jmp	$LN1@qt_metacal
$LN2@qt_metacal:
; Line 117
	cmp	DWORD PTR _c$[rsp], 1
	je	SHORT $LN5@qt_metacal
	cmp	DWORD PTR _c$[rsp], 2
	je	SHORT $LN5@qt_metacal
	cmp	DWORD PTR _c$[rsp], 3
	je	SHORT $LN5@qt_metacal
	cmp	DWORD PTR _c$[rsp], 11
	jne	SHORT $LN3@qt_metacal
$LN5@qt_metacal:
; Line 118
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_static_metacall@RootContatItem@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; RootContatItem::qt_static_metacall
; Line 119
	mov	eax, DWORD PTR _id$[rsp]
	dec	eax
	mov	DWORD PTR _id$[rsp], eax
	jmp	SHORT $LN4@qt_metacal
$LN3@qt_metacal:
; Line 120
	cmp	DWORD PTR _c$[rsp], 4
	jne	SHORT $LN6@qt_metacal
; Line 121
	mov	eax, DWORD PTR _id$[rsp]
	dec	eax
	mov	DWORD PTR _id$[rsp], eax
	jmp	SHORT $LN7@qt_metacal
$LN6@qt_metacal:
; Line 122
	cmp	DWORD PTR _c$[rsp], 5
	jne	SHORT $LN8@qt_metacal
; Line 123
	mov	eax, DWORD PTR _id$[rsp]
	dec	eax
	mov	DWORD PTR _id$[rsp], eax
	jmp	SHORT $LN9@qt_metacal
$LN8@qt_metacal:
; Line 124
	cmp	DWORD PTR _c$[rsp], 6
	jne	SHORT $LN10@qt_metacal
; Line 125
	mov	eax, DWORD PTR _id$[rsp]
	dec	eax
	mov	DWORD PTR _id$[rsp], eax
	jmp	SHORT $LN11@qt_metacal
$LN10@qt_metacal:
; Line 126
	cmp	DWORD PTR _c$[rsp], 7
	jne	SHORT $LN12@qt_metacal
; Line 127
	mov	eax, DWORD PTR _id$[rsp]
	dec	eax
	mov	DWORD PTR _id$[rsp], eax
	jmp	SHORT $LN13@qt_metacal
$LN12@qt_metacal:
; Line 128
	cmp	DWORD PTR _c$[rsp], 8
	jne	SHORT $LN14@qt_metacal
; Line 129
	mov	eax, DWORD PTR _id$[rsp]
	dec	eax
	mov	DWORD PTR _id$[rsp], eax
$LN14@qt_metacal:
$LN13@qt_metacal:
$LN11@qt_metacal:
$LN9@qt_metacal:
$LN7@qt_metacal:
$LN4@qt_metacal:
; Line 132
	mov	eax, DWORD PTR _id$[rsp]
$LN1@qt_metacal:
; Line 133
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacall@RootContatItem@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; RootContatItem::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_clname$ = 56
?qt_metacast@RootContatItem@@UEAAPEAXPEBD@Z PROC	; RootContatItem::qt_metacast
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_rootcontatitem.cpp
; Line 102
$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 103
	cmp	QWORD PTR _clname$[rsp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 104
	lea	rdx, OFFSET FLAT:?qt_meta_stringdata_RootContatItem@@3Uqt_meta_stringdata_RootContatItem_t@@B+48
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 105
	mov	rax, QWORD PTR this$[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 106
	mov	rdx, QWORD PTR _clname$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacast@QLabel@@UEAAPEAXPEBD@Z
$LN1@qt_metacas:
; Line 107
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacast@RootContatItem@@UEAAPEAXPEBD@Z ENDP	; RootContatItem::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = 32
this$ = 64
?metaObject@RootContatItem@@UEBAPEBUQMetaObject@@XZ PROC ; RootContatItem::metaObject
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_rootcontatitem.cpp
; Line 97
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 98
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	QWORD PTR [rax+40], 0
	je	SHORT $LN3@metaObject
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	rcx, rax
	call	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
	mov	QWORD PTR tv82[rsp], rax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@RootContatItem@@2UQMetaObject@@B ; RootContatItem::staticMetaObject
	mov	QWORD PTR tv82[rsp], rax
$LN4@metaObject:
	mov	rax, QWORD PTR tv82[rsp]
; Line 99
	add	rsp, 56					; 00000038H
	ret	0
?metaObject@RootContatItem@@UEBAPEBUQMetaObject@@XZ ENDP ; RootContatItem::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File e:\qt\5.9.6\msvc2017_64\include\qtcore\qscopedpointer.h
; Line 117
	mov	QWORD PTR [rsp+8], rcx
; Line 118
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 8
__formal$ = 16
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_rootcontatitem.cpp
; Line 136
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 8
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File d:\qtvs\qtqq\qtqq\x64\debug\moc\moc_rootcontatitem.cpp
; Line 136
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
