; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27048.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG123016 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG123017 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG123018 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG123311 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG123312 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG123313 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG124098 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG124099 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG124100 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG124441 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG124442 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG124443 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
?qt_meta_stringdata_TcpSocket@@3Uqt_meta_stringdata_TcpSocket_t@@B DD 0ffffffffH ; qt_meta_stringdata_TcpSocket
	DD	09H
	DD	00H
	ORG $+4
	DQ	00000000000000a8H
	DD	0ffffffffH
	DD	017H
	DD	00H
	ORG $+4
	DQ	000000000000009aH
	DD	0ffffffffH
	DD	00H
	DD	00H
	ORG $+4
	DQ	000000000000009aH
	DD	0ffffffffH
	DD	0bH
	DD	00H
	ORG $+4
	DQ	0000000000000083H
	DD	0ffffffffH
	DD	016H
	DD	00H
	ORG $+4
	DQ	0000000000000077H
	DD	0ffffffffH
	DD	0dH
	DD	00H
	ORG $+4
	DQ	0000000000000076H
	DD	0ffffffffH
	DD	012H
	DD	00H
	ORG $+4
	DQ	000000000000006cH
	DB	054H
	DB	063H
	DB	070H
	DB	053H
	DB	06fH
	DB	063H
	DB	06bH
	DB	065H
	DB	074H
	DB	00H
	DB	073H
	DB	069H
	DB	067H
	DB	06eH
	DB	061H
	DB	06cH
	DB	047H
	DB	065H
	DB	074H
	DB	044H
	DB	061H
	DB	074H
	DB	061H
	DB	046H
	DB	072H
	DB	06fH
	DB	06dH
	DB	043H
	DB	06cH
	DB	069H
	DB	065H
	DB	06eH
	DB	074H
	DB	00H
	DB	00H
	DB	051H
	DB	042H
	DB	079H
	DB	074H
	DB	065H
	DB	041H
	DB	072H
	DB	072H
	DB	061H
	DB	079H
	DB	026H
	DB	00H
	DB	073H
	DB	069H
	DB	067H
	DB	06eH
	DB	061H
	DB	06cH
	DB	043H
	DB	06cH
	DB	069H
	DB	065H
	DB	06eH
	DB	074H
	DB	044H
	DB	069H
	DB	073H
	DB	063H
	DB	06fH
	DB	06eH
	DB	06eH
	DB	065H
	DB	063H
	DB	074H
	DB	00H
	DB	06fH
	DB	06eH
	DB	052H
	DB	065H
	DB	063H
	DB	065H
	DB	069H
	DB	076H
	DB	065H
	DB	044H
	DB	061H
	DB	074H
	DB	061H
	DB	00H
	DB	06fH
	DB	06eH
	DB	043H
	DB	06cH
	DB	069H
	DB	065H
	DB	06eH
	DB	074H
	DB	044H
	DB	069H
	DB	073H
	DB	063H
	DB	06fH
	DB	06eH
	DB	06eH
	DB	065H
	DB	063H
	DB	074H
	DB	00H
	ORG $+1
?qt_meta_data_TcpSocket@@3QBIB DD 07H			; qt_meta_data_TcpSocket
	DD	00H
	DD	00H
	DD	00H
	DD	04H
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	02H
	DD	01H
	DD	02H
	DD	022H
	DD	02H
	DD	06H
	DD	04H
	DD	01H
	DD	027H
	DD	02H
	DD	06H
	DD	05H
	DD	00H
	DD	02aH
	DD	02H
	DD	08H
	DD	06H
	DD	00H
	DD	02bH
	DD	02H
	DD	08H
	DD	02bH
	DD	080000003H
	DD	02H
	DD	02H
	DD	02H
	DD	02bH
	DD	02H
	DD	02H
	DD	02bH
	DD	02bH
	DD	00H
	ORG $+4
$SG120933 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+5
$SG120934 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG120935 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG122721 DB	'e:\qt\5.9.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+13
$SG122722 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG122723 DB	'qRegisterNormalizedMetaType', 00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@TcpSocket@@UEBAPEBUQMetaObject@@XZ	; TcpSocket::metaObject
PUBLIC	?qt_metacast@TcpSocket@@UEAAPEAXPEBD@Z		; TcpSocket::qt_metacast
PUBLIC	?qt_metacall@TcpSocket@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; TcpSocket::qt_metacall
PUBLIC	?qt_static_metacall@TcpSocket@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; TcpSocket::qt_static_metacall
PUBLIC	?signalGetDataFromClient@TcpSocket@@QEAAXAEAVQByteArray@@H@Z ; TcpSocket::signalGetDataFromClient
PUBLIC	?signalClientDisconnect@TcpSocket@@QEAAXH@Z	; TcpSocket::signalClientDisconnect
PUBLIC	?staticMetaObject@TcpSocket@@2UQMetaObject@@B	; TcpSocket::staticMetaObject
EXTRN	strcmp:PROC
EXTRN	__imp_?activate@QMetaObject@@SAXPEAVQObject@@PEBU1@HPEAPEAX@Z:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QTcpSocket@@UEAAPEAXPEBD@Z:PROC
EXTRN	__imp_?qt_metacall@QTcpSocket@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC
EXTRN	?onReceiveData@TcpSocket@@AEAAXXZ:PROC		; TcpSocket::onReceiveData
EXTRN	?onClientDisconnect@TcpSocket@@AEAAXXZ:PROC	; TcpSocket::onClientDisconnect
EXTRN	__GSHandlerCheck:PROC
EXTRN	__security_check_cookie:PROC
EXTRN	__imp_?staticMetaObject@QTcpSocket@@2UQMetaObject@@B:BYTE
EXTRN	__security_cookie:QWORD
_BSS	SEGMENT
?staticMetaObject@TcpSocket@@2UQMetaObject@@B DB 030H DUP (?) ; TcpSocket::staticMetaObject
_BSS	ENDS
pdata	SEGMENT
$pdata$?metaObject@TcpSocket@@UEBAPEBUQMetaObject@@XZ DD imagerel $LN5
	DD	imagerel $LN5+88
	DD	imagerel $unwind$?metaObject@TcpSocket@@UEBAPEBUQMetaObject@@XZ
$pdata$?qt_metacast@TcpSocket@@UEAAPEAXPEBD@Z DD imagerel $LN5
	DD	imagerel $LN5+75
	DD	imagerel $unwind$?qt_metacast@TcpSocket@@UEAAPEAXPEBD@Z
$pdata$?qt_metacall@TcpSocket@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN9
	DD	imagerel $LN9+174
	DD	imagerel $unwind$?qt_metacall@TcpSocket@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?qt_static_metacall@TcpSocket@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN15
	DD	imagerel $LN15+308
	DD	imagerel $unwind$?qt_static_metacall@TcpSocket@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?signalGetDataFromClient@TcpSocket@@QEAAXAEAVQByteArray@@H@Z DD imagerel $LN3
	DD	imagerel $LN3+107
	DD	imagerel $unwind$?signalGetDataFromClient@TcpSocket@@QEAAXAEAVQByteArray@@H@Z
$pdata$?signalClientDisconnect@TcpSocket@@QEAAXH@Z DD imagerel $LN3
	DD	imagerel $LN3+66
	DD	imagerel $unwind$?signalClientDisconnect@TcpSocket@@QEAAXH@Z
pdata	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@TcpSocket@@2P6AXXZEA@@3P6AXXZEA DQ FLAT:??__E?staticMetaObject@TcpSocket@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@TcpSocket@@2P6AXXZEA@@3P6AXXZEA
CRT$XCU	ENDS
xdata	SEGMENT
$unwind$?metaObject@TcpSocket@@UEBAPEBUQMetaObject@@XZ DD 010901H
	DD	06209H
$unwind$?qt_metacast@TcpSocket@@UEAAPEAXPEBD@Z DD 010e01H
	DD	0420eH
$unwind$?qt_metacall@TcpSocket@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	04217H
$unwind$?qt_static_metacall@TcpSocket@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	08217H
$unwind$?signalGetDataFromClient@TcpSocket@@QEAAXAEAVQByteArray@@H@Z DD 012219H
	DD	08213H
	DD	imagerel __GSHandlerCheck
	DD	038H
$unwind$?signalClientDisconnect@TcpSocket@@QEAAXH@Z DD 010d01H
	DD	0620dH
xdata	ENDS
; Function compile flags: /Odtp
;	COMDAT ??__E?staticMetaObject@TcpSocket@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@TcpSocket@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'TcpSocket::staticMetaObject'', COMDAT
; File d:\qt_workspace\qtqq_server\qtqq_server\x64\debug\moc\moc_tcpsocket.cpp
; Line 113
	mov	rax, QWORD PTR __imp_?staticMetaObject@QTcpSocket@@2UQMetaObject@@B
	mov	QWORD PTR ?staticMetaObject@TcpSocket@@2UQMetaObject@@B, rax
	lea	rax, OFFSET FLAT:?qt_meta_stringdata_TcpSocket@@3Uqt_meta_stringdata_TcpSocket_t@@B
	mov	QWORD PTR ?staticMetaObject@TcpSocket@@2UQMetaObject@@B+8, rax
; Line 114
	lea	rax, OFFSET FLAT:?qt_meta_data_TcpSocket@@3QBIB
	mov	QWORD PTR ?staticMetaObject@TcpSocket@@2UQMetaObject@@B+16, rax
	lea	rax, OFFSET FLAT:?qt_static_metacall@TcpSocket@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; TcpSocket::qt_static_metacall
	mov	QWORD PTR ?staticMetaObject@TcpSocket@@2UQMetaObject@@B+24, rax
	mov	QWORD PTR ?staticMetaObject@TcpSocket@@2UQMetaObject@@B+32, 0
	mov	QWORD PTR ?staticMetaObject@TcpSocket@@2UQMetaObject@@B+40, 0
	ret	0
??__E?staticMetaObject@TcpSocket@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'TcpSocket::staticMetaObject''
text$di	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_a$ = 32
this$ = 64
_t1$ = 72
?signalClientDisconnect@TcpSocket@@QEAAXH@Z PROC	; TcpSocket::signalClientDisconnect
; File d:\qt_workspace\qtqq_server\qtqq_server\x64\debug\moc\moc_tcpsocket.cpp
; Line 157
$LN3:
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 158
	mov	QWORD PTR _a$[rsp], 0
	lea	rax, QWORD PTR _t1$[rsp]
	mov	QWORD PTR _a$[rsp+8], rax
; Line 159
	lea	r9, QWORD PTR _a$[rsp]
	mov	r8d, 1
	lea	rdx, OFFSET FLAT:?staticMetaObject@TcpSocket@@2UQMetaObject@@B ; TcpSocket::staticMetaObject
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?activate@QMetaObject@@SAXPEAVQObject@@PEBU1@HPEAPEAX@Z
; Line 160
	add	rsp, 56					; 00000038H
	ret	0
?signalClientDisconnect@TcpSocket@@QEAAXH@Z ENDP	; TcpSocket::signalClientDisconnect
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_a$ = 32
__$ArrayPad$ = 56
this$ = 80
_t1$ = 88
_t2$ = 96
?signalGetDataFromClient@TcpSocket@@QEAAXAEAVQByteArray@@H@Z PROC ; TcpSocket::signalGetDataFromClient
; File d:\qt_workspace\qtqq_server\qtqq_server\x64\debug\moc\moc_tcpsocket.cpp
; Line 150
$LN3:
	mov	DWORD PTR [rsp+24], r8d
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 72					; 00000048H
	mov	rax, QWORD PTR __security_cookie
	xor	rax, rsp
	mov	QWORD PTR __$ArrayPad$[rsp], rax
; Line 151
	mov	QWORD PTR _a$[rsp], 0
	mov	rax, QWORD PTR _t1$[rsp]
	mov	QWORD PTR _a$[rsp+8], rax
	lea	rax, QWORD PTR _t2$[rsp]
	mov	QWORD PTR _a$[rsp+16], rax
; Line 152
	lea	r9, QWORD PTR _a$[rsp]
	xor	r8d, r8d
	lea	rdx, OFFSET FLAT:?staticMetaObject@TcpSocket@@2UQMetaObject@@B ; TcpSocket::staticMetaObject
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?activate@QMetaObject@@SAXPEAVQObject@@PEBU1@HPEAPEAX@Z
; Line 153
	mov	rcx, QWORD PTR __$ArrayPad$[rsp]
	xor	rcx, rsp
	call	__security_check_cookie
	add	rsp, 72					; 00000048H
	ret	0
?signalGetDataFromClient@TcpSocket@@QEAAXAEAVQByteArray@@H@Z ENDP ; TcpSocket::signalGetDataFromClient
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv69 = 32
_t$1 = 40
result$2 = 48
_o$ = 80
_c$ = 88
_id$ = 96
_a$ = 104
?qt_static_metacall@TcpSocket@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; TcpSocket::qt_static_metacall
; File d:\qt_workspace\qtqq_server\qtqq_server\x64\debug\moc\moc_tcpsocket.cpp
; Line 82
$LN15:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 72					; 00000048H
; Line 83
	cmp	DWORD PTR _c$[rsp], 0
	jne	$LN4@qt_static_
; Line 84
	mov	rax, QWORD PTR _o$[rsp]
	mov	QWORD PTR _t$1[rsp], rax
; Line 86
	mov	eax, DWORD PTR _id$[rsp]
	mov	DWORD PTR tv69[rsp], eax
	cmp	DWORD PTR tv69[rsp], 0
	je	SHORT $LN6@qt_static_
	cmp	DWORD PTR tv69[rsp], 1
	je	SHORT $LN7@qt_static_
	cmp	DWORD PTR tv69[rsp], 2
	je	SHORT $LN8@qt_static_
	cmp	DWORD PTR tv69[rsp], 3
	je	SHORT $LN9@qt_static_
	jmp	SHORT $LN10@qt_static_
$LN6@qt_static_:
; Line 87
	mov	eax, 8
	imul	rax, rax, 2
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	ecx, 8
	imul	rcx, rcx, 1
	mov	r8d, DWORD PTR [rax]
	mov	rax, QWORD PTR _a$[rsp]
	mov	rdx, QWORD PTR [rax+rcx]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?signalGetDataFromClient@TcpSocket@@QEAAXAEAVQByteArray@@H@Z ; TcpSocket::signalGetDataFromClient
	jmp	SHORT $LN2@qt_static_
$LN7@qt_static_:
; Line 88
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?signalClientDisconnect@TcpSocket@@QEAAXH@Z ; TcpSocket::signalClientDisconnect
	jmp	SHORT $LN2@qt_static_
$LN8@qt_static_:
; Line 89
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?onReceiveData@TcpSocket@@AEAAXXZ	; TcpSocket::onReceiveData
	jmp	SHORT $LN2@qt_static_
$LN9@qt_static_:
; Line 90
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?onClientDisconnect@TcpSocket@@AEAAXXZ	; TcpSocket::onClientDisconnect
$LN10@qt_static_:
$LN2@qt_static_:
; Line 93
	jmp	SHORT $LN5@qt_static_
$LN4@qt_static_:
	cmp	DWORD PTR _c$[rsp], 10
	jne	SHORT $LN11@qt_static_
; Line 94
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	QWORD PTR result$2[rsp], rax
; Line 97
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	lea	rcx, OFFSET FLAT:?signalGetDataFromClient@TcpSocket@@QEAAXAEAVQByteArray@@H@Z ; TcpSocket::signalGetDataFromClient
	cmp	QWORD PTR [rax], rcx
	jne	SHORT $LN12@qt_static_
; Line 98
	mov	rax, QWORD PTR result$2[rsp]
	mov	DWORD PTR [rax], 0
; Line 99
	jmp	SHORT $LN1@qt_static_
$LN12@qt_static_:
; Line 104
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	lea	rcx, OFFSET FLAT:?signalClientDisconnect@TcpSocket@@QEAAXH@Z ; TcpSocket::signalClientDisconnect
	cmp	QWORD PTR [rax], rcx
	jne	SHORT $LN13@qt_static_
; Line 105
	mov	rax, QWORD PTR result$2[rsp]
	mov	DWORD PTR [rax], 1
$LN13@qt_static_:
$LN11@qt_static_:
$LN5@qt_static_:
$LN1@qt_static_:
; Line 110
	add	rsp, 72					; 00000048H
	ret	0
?qt_static_metacall@TcpSocket@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; TcpSocket::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@TcpSocket@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; TcpSocket::qt_metacall
; File d:\qt_workspace\qtqq_server\qtqq_server\x64\debug\moc\moc_tcpsocket.cpp
; Line 132
$LN9:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 133
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacall@QTcpSocket@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
	mov	DWORD PTR _id$[rsp], eax
; Line 134
	cmp	DWORD PTR _id$[rsp], 0
	jge	SHORT $LN2@qt_metacal
; Line 135
	mov	eax, DWORD PTR _id$[rsp]
	jmp	SHORT $LN1@qt_metacal
$LN2@qt_metacal:
; Line 136
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN3@qt_metacal
; Line 137
	cmp	DWORD PTR _id$[rsp], 4
	jge	SHORT $LN5@qt_metacal
; Line 138
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_static_metacall@TcpSocket@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; TcpSocket::qt_static_metacall
$LN5@qt_metacal:
; Line 139
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 4
	mov	DWORD PTR _id$[rsp], eax
	jmp	SHORT $LN4@qt_metacal
$LN3@qt_metacal:
; Line 140
	cmp	DWORD PTR _c$[rsp], 12
	jne	SHORT $LN6@qt_metacal
; Line 141
	cmp	DWORD PTR _id$[rsp], 4
	jge	SHORT $LN7@qt_metacal
; Line 142
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	DWORD PTR [rax], -1
$LN7@qt_metacal:
; Line 143
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 4
	mov	DWORD PTR _id$[rsp], eax
$LN6@qt_metacal:
$LN4@qt_metacal:
; Line 145
	mov	eax, DWORD PTR _id$[rsp]
$LN1@qt_metacal:
; Line 146
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacall@TcpSocket@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; TcpSocket::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_clname$ = 56
?qt_metacast@TcpSocket@@UEAAPEAXPEBD@Z PROC		; TcpSocket::qt_metacast
; File d:\qt_workspace\qtqq_server\qtqq_server\x64\debug\moc\moc_tcpsocket.cpp
; Line 124
$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 125
	cmp	QWORD PTR _clname$[rsp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 126
	lea	rdx, OFFSET FLAT:?qt_meta_stringdata_TcpSocket@@3Uqt_meta_stringdata_TcpSocket_t@@B+168
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 127
	mov	rax, QWORD PTR this$[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 128
	mov	rdx, QWORD PTR _clname$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacast@QTcpSocket@@UEAAPEAXPEBD@Z
$LN1@qt_metacas:
; Line 129
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacast@TcpSocket@@UEAAPEAXPEBD@Z ENDP		; TcpSocket::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = 32
this$ = 64
?metaObject@TcpSocket@@UEBAPEBUQMetaObject@@XZ PROC	; TcpSocket::metaObject
; File d:\qt_workspace\qtqq_server\qtqq_server\x64\debug\moc\moc_tcpsocket.cpp
; Line 119
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 120
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	QWORD PTR [rax+40], 0
	je	SHORT $LN3@metaObject
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	rcx, rax
	call	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
	mov	QWORD PTR tv82[rsp], rax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@TcpSocket@@2UQMetaObject@@B ; TcpSocket::staticMetaObject
	mov	QWORD PTR tv82[rsp], rax
$LN4@metaObject:
	mov	rax, QWORD PTR tv82[rsp]
; Line 121
	add	rsp, 56					; 00000038H
	ret	0
?metaObject@TcpSocket@@UEBAPEBUQMetaObject@@XZ ENDP	; TcpSocket::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File e:\qt\5.9.6\msvc2017_64\include\qtcore\qscopedpointer.h
; Line 117
	mov	QWORD PTR [rsp+8], rcx
; Line 118
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 8
__formal$ = 16
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File d:\qt_workspace\qtqq_server\qtqq_server\x64\debug\moc\moc_tcpsocket.cpp
; Line 163
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 8
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File d:\qt_workspace\qtqq_server\qtqq_server\x64\debug\moc\moc_tcpsocket.cpp
; Line 163
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
